### ISSUE TITLE
Cannot change settings on iOS

### ISSUE THREAD

**Issue by uschmu** [owntracks/talk#102]
I cannot change any Settings in OwnTracks App on my iPhone. In particular, OwnTracks proposes only MQTT Connection, but I need http(s) for openHAB. Also, I cannot edit my User Name and tracker ID. I cancelled and re-installed  OwnTracks several times, with no success. How can I reset settings?

**Comment by jpmens** [comment]
@uschmu there is no body in your issue. What can we do for you?

Edited to add that OP had placed issue within HTML comment `<!--`

**Comment by jpmens** [comment]
Tap 3 times on next to the word `Settings` in the iOS app and you will have access to all the settings. Beware that this can be hard to grasp. Future versions of the iOS app will permit these settings to be edited without the 3-tap magic.

**Comment by ckrey** [comment]
When you tap on MQTT, you will get a choice
between MQTT and HTTP

**Comment by uschmu** [comment]
... just crazy - that‘s is!!! very unconvenient 😀 Many thanks for your hints
