### ISSUE TITLE
Just Some Feedback

### ISSUE THREAD

**Issue by boogymantoo** [owntracks/talk#103]
Good Day, we have been using owntracks to follow participants in an event, and we wanted to share our feedback with this community.

As a quick introduction: we (a friend and me) are both IT-veterans as well as volunteers for a non-profit organization. At least once a year, that npo organizes an event to raise funds (a.o. to fight poverty). The typical event would be to walk 100 kilometers within 30 hours, in teams of 4. Each edition attracts close to a thousand participants, or 250 teams. Our role is to develop and operate the applications:
- that follow the participants,
- and make their "*actual positions*" visible on the web.

This year, the "*format*" of that event had to be revised due to covid-19 restrictions. The revised format was one of the drivers to start using owntracks, to follow the position of the participants.

And now on to that feedback - I will limit myself to the "*headlines*" but feel free to ask for details on specific topics. Also, we would certainly appreciate to get your thoughts/ideas in return.

 - **the setup**:
	- we provided a configuration file to the participants, which they imported
	- at least one participant per team has owntracks "*activated*" during the event
	- either: participants in one team took turns in activating owntracks, or: they used a powerbank
	- the server is hosted by the npo, and running a typical LAMP stack
	- the server-side code is developed by us (but the ipr are with the npo)
  
 - **overall feedback** is positive: in general, owntracks works "*as it says on the tin*"

 - **specific feedback topics for Android**:
	- we used "*significant changes mode*" because it can be configured to work (a lot) more accurately than "*move mode*"; that is because in move mode, the location fix frequency is fixed to once per 30 seconds; increasing that frequency to once per 10 seconds causes a visible improvement of the accuracy (if you use HIGH_POWER mode, obviously)
	- we could not get the basic authentication to work (in HTTP mode) which is a real pity
	- some phone manufacturers cause a real PITA by "*killing*" the app when in background (actually, even when in foreground); feeding information into a website like dontkillmyapp.com could really help a lot
  
 - **specific feedback topics for iOS**:
	- we found that "*significant changes mode*" is not sufficiently accurate (for our goals)
		therefor we used "*move mode*" on iOS
	- "*move mode*" works well with owntracks in foreground but also with owntracks in background, as long as a "*location app using the gps*" is in foreground - like maps for example
	- at any rate, it's a real disadvantage that a location app must be in foreground: after reading and replying to an incoming message for example, people just forget to put owntracks back in foreground (understandably so)
	- given that we could not make use of basic authentication for everyone, we did not (even) try it out on iOS
	- the process to correctly import a configuration file seems to be depending on the version of iOS but in any case it is not "*easy*" (maybe Apple should have taught their users what a file is, after all)

**Comment by jpmens** [comment]
Hello @boogymantoo: thank you very much for this report. I think it’s safe to say all of us enjoy hearing about situations in which OwnTracks has successfully been used, and yours was a fun read!

I am sorry to hear that not all worked to your or your teams’ satisfaction. Let me pick out a couple of points:

* basic authentication _should_ work on our Android app, and if it doesn’t we’ll consider that a bug. If you or the person who found this can create an issue indicating how to reproduce it, we’d look into it
* move mode in iOS should work fine if you can keep the app in the foreground — something which might not always be possible
* basic authentication in HTTP mode on iOS works, but I understand you couldn’t use it because it wouldn’t work for every user involved (Android)
* the OTRC import isn’t easy, maybe; I’ve found it’s easiest when sending myself or my users an OTRC via e-mail.

I must say I’m very happy about your _overall feedback_; that is really good.

**Comment by boogymantoo** [comment]
> Hello @boogymantoo: thank you very much for this report. I think it’s safe to say all of us enjoy hearing about situations in which OwnTracks has successfully been used, and yours was a fun read!
> 
> [ ... ]
> 
> * basic authentication in HTTP mode on iOS works, but I understand you couldn’t use it because it wouldn’t work for every user involved (Android)
> * the OTRC import isn’t easy, maybe; I’ve found it’s easiest when sending myself or my users an OTRC via e-mail.
> 
> I must say I’m very happy about your _overall feedback_; that is really good.

Hello @jpmens ,

* We confirm that we are happy too. We're considering to use owntracks for the regular (read: *non-covid-19*) editions.
* Indeed, we wanted to have "*one single implementation*" - so either: everyone uses basic auth or: no-one uses basic auth.
* If a one-process-fits-all exists for the import of an otrc file, we are all ears :-)

Best regards,
And thanks,
Chris.

**Comment by jpmens** [comment]
> If a one-process-fits-all exists for the import of an otrc file, we are all ears 

I believe it does, as long as the devices have access to an e-mail account. In both iOS and Android we can open an OwnTracks configuration file (`.otrc`) from an email attachment, and that reconfigures the apps. I think that's what you're after?

**Comment by boogymantoo** [comment]
> > If a one-process-fits-all exists for the import of an otrc file, we are all ears
> 
> I believe it does, as long as the devices have access to an e-mail account. In both iOS and Android we can open an OwnTracks configuration file (`.otrc`) from an email attachment, and that reconfigures the apps. I think that's what you're after?

Sending a mail with an attachment comes close, but alas there are cases where that did not work either:
* for people who use a browser i.s.o. a real email client, it did not work (especially on iOS)
* we had a few participants using an old Android version (v5.1 iirc) - no association between file extension and app
* and a few participants who had a "*managed device*" on which the absence of permissions blocked this functionality

On Android we concluded that placing the .otrc file on a google drive, and mailing a "*shared link*" to that file, worked in almost all cases - except on versions where file associations do not work.

On iOS we concluded that attaching the file to a mail worked best - but not in the two cases listed above (browser i.s.o. mail client, managed device).

Best regards,
Chris.

**Comment by jpmens** [comment]
Bonsoir @boogymantoo, I've taken an iPhone for a drive respectively a short walk. With settings recommended by @ckrey, namely

```
LocatorDisplacement: 50
LocatorInterval: 30 
```

instead of their defaults (double the values), I get quite reasonable results from _Move Mode_ and this **without** running a navigation app. To be clear: OwnTracks was set to move mode, and I switched the phone off.

Here's a drive through a town:

![rabbit-6816](https://user-images.githubusercontent.com/60706/93002619-97aea400-f538-11ea-826e-4268916b4445.png)

and here's a short walk of a block, the block on the right: 

![rabbit-6817](https://user-images.githubusercontent.com/60706/93002648-c167cb00-f538-11ea-960c-54e6303cec30.png)
(yes, I'm a lazy bum!)

I hope that helps?

**Comment by boogymantoo** [comment]
Hi @jpmens ,

Thanks for that feedback.

What we used (on iOS), was move mode with:
* locatorDisplacement = 200
* locatorInterval = 90

And then:
* **either** keep owntracks in foreground (screen on or screen off)
* **or** owntracks in background **in combination with** a *gps using app* in foreground

Those settings gave us good results. But (as written in our feedback) **significant changes mode** (on iOS) just did not give sufficient accuracy. 

And, alas, people sometimes forgot to bring owntracks back to foreground after using another app.

Best regards,
Chris.

PS: I believe I just *understood* why you emphasized: *and this **without** running a navigation app*
=> I am sorry for the confusion I caused... With my original comment "*it's a real disadvantage that a location app must be in foreground*" I actually referred to the *general **Apple** rule* which actually prohibits the use of accurate location apps in background.

**Comment by jpmens** [comment]
Is it possible that your users are killing the iOS app by swiping it out? We see that happen a lot by people who erroneously believe they can "help" the iOS multitasking by killing apps. :-(

**Comment by boogymantoo** [comment]
> Is it possible that your users are killing the iOS app by swiping it out? We see that happen a lot by people who erroneously believe they can "help" the iOS multitasking by killing apps. :-(

I believe some users have "*helped*" iOS in that way, yes. But I don't think there would have been many who did so.
As said, overall owntracks lived up to its promise(s)!

Thanks again,
Chris.
