### ISSUE TITLE
Set location of devices remotely by the server

### ISSUE THREAD

**Issue by dl5dla** [owntracks/talk#107]
Hi,
I am using owntracks on iPhone and connect it to my local MQTT server. Is there a possibility to
- remotely create dummy devices on the phone within the owntracks app?
- to set or change locations of such devices remotely from the server back to the phone?

The idea behind is that I would like to show devices on the map which are not tracked by the owntracks app themself. E.g., I get positions of weather ballons via radio link onto my server and would like to show the position of the balloon together with my current (tracked) position on the map.

**Comment by jpmens** [comment]
Sure, we do a lot of that! Publish your “friends” To the same broker you use, using a different topic, eg owntracks/weather/balloon1 in OwnTracks JSON format. Ensure your broker ACL permits your iPhone to receive those topics, and you’ll see them on the OwnTracks map and friends list. 

Our Booklet also discusses CARDs you can publish for your balloons to give them meaningful names and optional icons.

**Comment by dl5dla** [comment]
Thanks a lot for the information. That lets me start :-). Meanwhile (for test) one balloon is already "dancing" on the map. Realy a promising software with lot of oppprtunities.

**Comment by jpmens** [comment]
🎈
