### ISSUE TITLE
Tracks on iPhone map

### ISSUE THREAD

**Issue by dl5dla** [owntracks/talk#108]
Hi,
is it possible (or considered for future versions) to show tracks and past locations on the map, so that one can see where he was walking in the ast hours?

**Comment by ckrey** [comment]
It is already implemented. Just tap to n the marker. 
The number of past positions stored is controlled by the `Positions` parameter, which defaults to 50.

**Comment by dl5dla** [comment]
Thank you for that information - was quite new for me. It looks like that the track disappears as soon as the location is changing (in my case this happens each few seconds). Is there a possiblity to keep the track on the map any matter the location changes?

**Comment by ckrey** [comment]
It disappears when a new position is added
