### ISSUE TITLE
Support for bluetooth devices connected to the iPhone?

### ISSUE THREAD

**Issue by dl5dla** [owntracks/talk#109]
Some kind of a feature request or idea, not sure whether this technically possible at all or fitting into the intended framework of owntracks:

I have a small device (based on an ESP32 microcontroller), which receives positions of weather balloons via radio link. The idea is to send these received positions via bluetooth to the phone. Owntracks should deal with these location data in the same way as it is doing with the phone's internal GPS data and send the data to the server.

Currently, as a workaround I am thinking about connecting the device via WLAN/thethering to the phone and passing the data from there directly to the server, which then sends the positions back to the phone via MQTT. Drawback is the much higher power consumption of the  WLAN connection.

**Comment by jpmens** [comment]
Thanks for the suggestion, but we won't do that.

Your ESP32 microcontroller can eaily enough publish its data via MQTT, and as you rightly say, you can tether it to your phone, so there's no need to complicate our apps.
