### ISSUE TITLE
Owntracks on Android Subscribe Problem

### ISSUE THREAD

**Issue by robert1233** [owntracks/talk#11]
Hi, I'm running Owntracks on my Galaxy S5. I might be misunderstanding the documentation, but here goes. 

I'm trying to show the location of a Raspberry Pi on my phone's Owntracks. Documentation says Owntracks subscribe to owntracks/+/+. When I try to publish from my Pi, (using Python), I get an error saying that wildcards aren't allowed (referring to the '+' signs). I'm publishing to broker.hivemq.com for now.

Any help/teachings welcome. Thanks

**Comment by jpmens** [comment]
OwnTracks on your phone indeed subscribes to `owntracks/+/+`; these wildcards mean that you would, say, publish from your Raspi as `owntracks/robert1233/rpi`, assuming a username of `robert1233` and a "device name" of `rpi`. I think you'll then find your Raspi will show up as a friend on your phone, assuming you are publishing JSON data as standardized in our Booklet.

**Comment by robert1233** [comment]
Thank you so much for the quick reply, I'm not great with JSON, and only want to send the lat, and lon location values. Would the JSON look like this:

{
    "_type" : "location",
    "lat" : "38.424430",
    "lon" : "-82.438547"
}

Thank you once again.

**Comment by jpmens** [comment]
You'll probably also need [see JSON in Booklet](http://owntracks.org/booklet/tech/json/) `tst`, and `tid`. In Python  you can create `tst` with

```python
import time

tst = int(time.time())
```

**Comment by robert1233** [comment]
After formatting the JSON correctly and adding the tst and tid values, it worked perfectly, thank you so much! And thank you for the quick reply.

**Comment by jpmens** [comment]
Glad it worked. With a bit more effort you can put up a card for your Raspi, showing a small icon or some such. Good luck. ;-) [Card documentation](http://owntracks.org/booklet/features/card/).
