### ISSUE TITLE
Owntracks over XMPP and OMEMO

### ISSUE THREAD

**Issue by karmanyaahm** [owntracks/talk#110]
This is a just an idea right now but I've been thinking about if Owntracks could run over XMPP (with OMEMO perhaps).

Advantages:
- E2E encryption is easier to implement since there are many XMPP apps that the implementation can be based off of.
- E2E enables a much wider audience to use Owntracks with existing public XMPP infrastructure without compromising security.
- Recorder doesn't have to be a separate component

Disadvantages:
- MQTT topics model might have to be rethought (though HTTP mode is a single channel?)
- Implementing this in the apps would be a lot of work.
- I'm not sure how integrations with Home Assistant would be (I haven't used those)
 
This is still just an idea and I'm not an expert on network protocols, so I don't know if this will be feasible but I would love to hear everyone's thoughts on this.

**Comment by jpmens** [comment]
No.

**Comment by jpmens** [comment]
We already implement optional E2E encryption and have MQTT or HTTP over TLS, and we’ve no resources to re-implement apps and tools. 

Thanks for the idea, but we won’t do this.

**Comment by karmanyaahm** [comment]
Ok, thanks for maintaining Owntracks!
