### ISSUE TITLE
Pet Tracking

### ISSUE THREAD

**Issue by NiallDarwin** [owntracks/talk#111]
Hi,

What you've done so far is really great. I found your project because of a particular requirement I have. 

I have a wandering dog and an old phone. I want to attach the two and then setup a geo-fence. When the dog crosses the boundary I'd like to receive a warning on my own device and possibly play a sound on the 'dog phone' No apps seem to exist specifically to do this and I think there would be a market for it. Sadly I have zero coding skills so I cannot make it happen.

If anyone wants to discuss & progress this I'm happy to be involved.

**Comment by jpmens** [comment]
With the exception of playing a sound for the dog, OwnTracks can do this, and you'll likely not need coding. Set up the two devices as "Friends" on OwnTracks and define a monitoring region on dog's device; your device will be notified when the dog enters or leaves the region.

Our [Booklet](https://owntracks.org/booklet/) might be a source of inspiration.

**Comment by NiallDarwin** [comment]
Hi @jpmens  thank you for responding to my issue.
I feel you suffer from the same affliction many skilled people have which is underestimating how skilled you are. Anything which involves, "a close look at the documentation of your router" (https://owntracks.org/booklet/guide/broker/) is almost certainly beyond the attention/capabilities of the casual user. While technically setting up an MQQT server isn't coding it is a lot more than drawing a circle on a map and selecting the 'notify me if device is outside this region' checkbox!
Don't get me wrong, I don't mind doing difficult things when they interest me and align with my abilities. IT always seems like a quicksand trap and I avoid it if possible. See here for how this type of project usually goes with me: https://xkcd.com/349/

**Comment by jpmens** [comment]
Ok, @NiallDarwin, then I'm afraid we're probably not the project you are looking for as it would require quite a bit of involvement on your side. I can't think of anything which would suit you, but maybe other people have good ideas.

**Comment by NiallDarwin** [comment]
No problem @jpmens . I've actually now started trying to setup an MQTT broker and its not going well! You're right, I'm probably better using something ready to go. Have a great Christmas :)
