### ISSUE TITLE
cached location data

### ISSUE THREAD

**Issue by vantino** [owntracks/talk#115]
Ciao

FIrst, fantastic concept and well implementation! Read all the doc`'s but didnt found my /q:

I would like to have the adriod/ios app to cache the location data while not connected to the internet.
Some devices dont have internet connections permanently.

Is there an option to cache data and submit to the recorder, once an inet connection is available ?

Thanks
Vantino

**Comment by jpmens** [comment]
Hello, and thanks for your notes.

What you want occurs automatically: when our apps cannot connect to the target broker/server they cache the location data until said time when they can. So I think that's precisely what you want.

**Comment by vantino** [comment]
Oh – absolutely, that’s it – thanks.
