### ISSUE TITLE
What does created_at mean in the json payload from an Android device?

### ISSUE THREAD

**Issue by TheQuickster** [owntracks/talk#116]
Not an issue but  something new/unknown. I've started seeing the following field coming from Owntracks 

"_type":"location","acc":22,"alt":257,"batt":93,"bs":1,**"created_at":1616985986,**"lat":xxxxxxxx,"lon":xxxxxxxxxx,"tid":"5","tst":1616985985,"vac":0,"vel":0}

Just trying to understand what the created_by means. Is that the actual time the point was created vrs when the data can be sent to the server (via http POST). I assumed tst was the creation time of the point? 

Does anybody know what this is about. I have not been able to find out what this means from the documentation.

**Comment by jpmens** [comment]
Thanks for noticing, and sorry we forgot to document this (I've done done so)

`created_at` identifies the time at which the message is constructed (vs. `tst` which is the timestamp of the GPS fix) _(iOS,Android)_
