### ISSUE TITLE
Can the docker image be started without MQTT?

### ISSUE THREAD

**Issue by eigenphase** [owntracks/talk#122]
As noted [here](https://github.com/owntracks/talk/issues/121), I'd like to not use MQTT but HTTPS directly.

When I want to start the recorder via docker:

```
root@harbor:~# docker run -p 8083:8083 -v owntracks_store:/store owntracks/recorder
ot-recorder[12]: version 0.8.6 starting with STORAGEDIR=/store
ot-recorder[12]: connecting to MQTT on localhost:1883 as clientID ot-recorder-f5f07bd642b3-12 without TLS
Error: Address not available
root@harbor:~#
```

I did not find a config flag to disable MQTT. Is this possible?

**Comment by eigenphase** [comment]
FYI, despite the disadvantages listed in https://github.com/owntracks/talk/issues/121, I decided to go with MQTT. I don't need it but I feel it's just how its "meant to be used".

I will still keep this open because someone else could be interested to know.

**Comment by growse** [comment]
Setting `OTR_PORT` to `0` disables the MQTT connection for the recorder for me.
