### ISSUE TITLE
Freezes immediately after start on Galaxy Watch 3

### ISSUE THREAD

**Issue by hgrossauer** [owntracks/talk#124]
The app freezes immediately after the start on my Galaxy Watch 3. All I see is a gray rectangle with some blue and gray icons around it, but there is no reaction when tapping on them.

I another forum I have read as a workaround I could switch my watch and the smartphone to English, but this is not an option for me. In case this is really the cause, could you make owntracks work in other locales than english as well?

**Comment by jpmens** [comment]
I don't think we've had anybody attempt this previously...

Can you tell us a bit about your use case and why you'd want that to be possible? What would OwnTracks on your watch do that it cannot do on your phone? Do you use the watch completely independently from the phone (i.e. is that even possible?)

**Comment by jpmens** [comment]
We've previoiusly been made aware of [OwnTracksOSM](https://github.com/wansti/OwntracksOSM) (from [our Booklet](https://owntracks.org/booklet/guide/clients/)), but that's quite a different bit of software.

**Comment by hgrossauer** [comment]
Ok, maybe I have mixed up owntrack and owntrackosm, I was not aware that this different software.

My use case is: When I go running I do not wan't to take my smartphone with me, but usually I carry my smartwatch. Sometimes I'd like to meet my partner later during the run, so it would be nice if she could just locate me using some app.

So what I am actually looking for is a method to real-time share my location from the Galaxy Watch 3, such that my partner can locate me.

**Comment by jpmens** [comment]
So, are you saying OwnTracks is freezing up on the watch, or are you saying OwnTracksOSM is doing so?

**Comment by hgrossauer** [comment]
I just found https://githubmemory.com/repo/wansti/OwntracksOSM/issues, which describes exactly my problem.
If I understand correctly this is a different software?

**Comment by jpmens** [comment]
That is, indeed, different software, so you'll have to report there, please.

Closing now.
