### ISSUE TITLE
Existing Servers

### ISSUE THREAD

**Issue by JeffCarpenter** [owntracks/talk#125]
Owntracks.org reads (emphasis mine):

> To get started, install OwnTracks on your smartphone. Afterwards you can connect it to an _existing server_ straight away or follow the guide in our Booklet to set up your own.

and I'm wondering where would be a good place to look for said existing server?

**Comment by jpmens** [comment]
We're considering doing a "Get started quickly" section for the Booklet and would appreciate your input on that.

That said, what was originally meant was our own Public respectively Hosted program, but we did away with that b/c it wasn't being used the way we thought it would be.

If you need a quick start there are a number of publicly available [MQTT brokers](https://mqtt.org/software/) you might want to look at (we do not endorse any of these), or if you have your own VPS you could install our Recorder on it and get started that way.

**Comment by jpmens** [comment]
We've created a [Quicksetup](https://owntracks.org/booklet/guide/quicksetup/) which  configures an MQTT server, our Recorder and Frontend with all bells and whistles as well as a configurable list of friends.
