### ISSUE TITLE
MQTT vs. HTTP

### ISSUE THREAD

**Issue by rhasselbaum** [owntracks/talk#131]
I'm considering a new installation and wondering if I should go with MQTT or HTTP. What are the pros/cons of each? A few things about my setup (if it matters):

* I'm using Android devices
* I have Home Assistant with MQTT already set up
* I want to share locations with a few "friends"

Thanks.

**Comment by jpmens** [comment]
Most of us are likely to recommend MQTT which was the original protocol supported by OwnTracks (originally named _MQTTitude_ :-) We later added support for HTTP thinking that some people would have an easier time setting up OwnTracks on a simple VPS using an existing nginx or Apache rather than configuring an MQTT broker, TLS for it, etc.

You write you already use MQTT for Home Assistant so there's not a single reason I can think of for you to use OwnTracks without MQTT, on the contrary: we support it in both our Android and iOS apps, so have at it, and if you run into trouble feel free to submit issues on the respective trackers.

**Comment by jpmens** [comment]
Closing as answered.

**Comment by eigenphase** [comment]
@jpmens, sorry to open this again. I have been using owntracks for years with separate MQTT and then I have another HA with MQTT instance.

> You write you already use MQTT for Home Assistant so there's not a single reason I can think of for you to use OwnTracks without MQTT, on the contrary: we support it in both our Android and iOS apps, so have at it, and if you run into trouble feel free to submit issues on the respective trackers.

Well, there is. Would you really want to expose your MQTT server over which you run zigbee2mqtt and other internal devices to the internet?

If not, and you are using a dedicated MQTT server, then we are back at OPs question -- and mine now:

Currently my owntracks setup is on a different system than HA but I am planning to combine and move owntracks to my homelab. I have the option to expose my EXISTING mqtt server (from HA) to the internet for owntracks. But I somewhat don't feel good about it. Locks, Garage, Lights, appliances, gates, water vales ... everything is controlled via Zigbee devices at home.

Then I could install a SEPARATE dedicated MQTT sever for owntracks. But that feels wasteful: More memory, more CPU, an additonal docker container ...

So I'm back to the question on whether I should just use the HTTP mode and call it the day? 
Or is there any reason why MQTT would be better, more stable, more lightweight etc?

**Comment by jpmens** [comment]
I see no difference between putting an MQTT broker on the Internet vs. an HTTP server. Both can be TLS protected, both offer authentication, and with broker ACLs you have fine granularity over which client can publish/subscribe to which topics. If your existing broker iss maintained and has the above capabilities, why not use it.

In my experience our OwnTracks apps behave much better over MQTT, and the Friends functionality works out of the box with broker ACLs.

**Comment by eigenphase** [comment]
> In my experience our OwnTracks apps behave much better over MQTT, and the Friends functionality works out of the box with broker ACLs.

Thanks, this is valuable feedback! I'll probably stay with MQTT then. Friends functionality I don't really need...

> I see no difference between putting an MQTT broker on the Internet vs. an HTTP server. Both can be TLS protected, both offer authentication, and with broker ACLs you have fine granularity over which client can publish/subscribe to which topics. If your existing broker iss maintained and has the above capabilities, why not use it.

The question is not dedicated MQTT vs dedicated HTTP, it's about _existing MQTT_ that is already being used for home automation vs _dedicated HTTP_.

Yes, I understand can use users/ACLs in mosquitto (and doing this). But exposing this MQTT server that exposes your HVAC, water heater, valves, locks and much more to the public internet wouldn't give you an uncomfortable feeling in your stomache?

It adds a substantial attack surface. In the unlikely event of a 0day issue in mosquitto, your whole home automation is compromised. What's worse, how about a simple mistake in the config? This is not as strange as it sounds.

Story from my own repertoire: Many years ago, I created a PHP script to control some smart plugs at home. I added a .htaccess to that folder with "Allow from 192.168.1.1/24; Deny from all". Worked like a charm. I forgot about this and just 2 weeks all of the sudden I saw that this is accessible via the internet! It seems sometime over the years some "AllowOverride" was modified upstream. Fortunately in this case, the PHP script was broken and nothing could happen. But could have ended up in a disaster. Similar for ACLs/users in mosquitto. One more thing to keep track. Best practice is to just not expose this mosquitto server in the first place. So, I think the only valid solution is a dedicated MQTT server for owntracks

**Comment by jpmens** [comment]
>I forgot about this and just 2 weeks all of the sudden I saw that this is accessible via the internet!

You have just confirmed to yourself that a HTTP server need not be more secure than an MQTT broker.

Whether or not something is "secure enough" is a decision that only you can take, and if  think a dedicated MQTT broker is worth your while then do it. Anything can be broken into given sufficient effort and time -- I don't think this requires discussion -- but it's your threat model which counts.

**Comment by eigenphase** [comment]
> You have just confirmed to yourself that a HTTP server need not be more secure than an MQTT broker.

Again, it's not the protocol I am talking about. Using HTTP in the case of owntracks only exposes access to the recorder ... and not, say, home assistant --> OK. Using a dedicated MQTT server only exposes access to owntracks related stuff --> OK. Using a shared MQTT can in the worst case expose access to all kinds of other stuff using that MQTT server. 

I agree, threat model is what counts, it's a personal decision but I believe in this instance it is "best practice" for nearly everyone to use a dedicated MQTT server.

**Comment by captcurrent** [comment]
Glad to finally find this.   I have been curious about it for some time...managed to get it work with HiveMQ as broker

**Comment by eigenphase** [comment]
Hmm, what did you find here specifically?

**Comment by captcurrent** [comment]
"Most of us are likely to recommend MQTT which was the original protocol supported by OwnTracks
