### ISSUE TITLE
What's your business model?

### ISSUE THREAD

**Issue by svillar** [owntracks/talk#133]
The app is free, great. So were do you get the money from?

Sorry if it sounds a bit harsh but before making my location potentially available to another third party, I'd like to know what's the deal.

Thanks

**Comment by jpmens** [comment]
We don't have a business model and we don't make location data available to third parties other than what occurs during reverse-geo resolution or map placement. (On our Android app you can configure a separate endpoint for reverse-geo lookups.)

When you configure OwnTracks apps you specify the address/hostname to which the location data is sent; these servers are beyond our control. We do not know what people do with the apps nor do we know where they are located as there's no "central" service. It's your data and you decide what to do with it.

We hope that people will sponsor us (see the `sponsor` button at the top of this page). Other than that, this is purely voluntary, and all of us work on OwnTracks during our spare time.

**Comment by jpmens** [comment]
Oh, and regarding the `sponsor` button at the top of the page: extremely few people have followed through with pressing it.

**Comment by svillar** [comment]
That's really awesome to hear! Thanks for the answer, you have gained at least a couple more users.

**Comment by svillar** [comment]
> That's really awesome to hear! Thanks for the answer, you have gained at least a couple more users.

and likely donors too

**Comment by jpmens** [comment]
> and likely donors too

We were secretly hoping you would say that! :-)
