### ISSUE TITLE
Feature: SmartBeacon mode for dynamic position reporting

### ISSUE THREAD

**Issue by oh2th** [owntracks/talk#135]
In the APRS community there is a common method to have dynamic interval based on movement speed, distance and change of course:
http://www.hamhud.net/hh2/smartbeacon.html
Using this method would decrease the amount of traffic needed to while keeping accurate enough.

**Comment by compuguy** [comment]
Site is no longer online, so here is a archive[.]is link: https://archive.is/A8F0g
