### ISSUE TITLE
Configure significant changes monitoring mode?

### ISSUE THREAD

**Issue by mm28ajos** [owntracks/talk#136]
Hey there,

great project! Works like a charm within half an hour.

One question regarding the settings: is it possible to configure the sensitivity of the significant changes monitoring mode i.e. can I set it to report on less significant position changes? I played around with the move monitoring mode but this is updating to frequently.

Best, thanks.

**Comment by connervieira** [comment]
I'm on Android, and I'm able to configured the update interval by navigating to Preferences > Advanced > Locator. There you can change the settings for both 'significant changes' mode as well as 'move' mode.

**Comment by jpmens** [comment]
Similar settings exist on iOS.
Closing as answered.
