### ISSUE TITLE
Sending waypoints to clients

### ISSUE THREAD

**Issue by Tobstr02** [owntracks/talk#139]
Hello, i'm currently working on my own owntracks http server and tried to send an waypoint from it to and end device as an answer of an location push.
The data gets received and counted in "received x updates" in the status page, but the new waypoint don't appear in the Waypoints ("Orte" in german) tab in the app.
Locations and configurations are working currently working perfectly.

Is it possible to add this to the app or is there another way for sending waypoints to an client?

Thanks in advance.

PS: Current json of an waypoint that i'm sending:
```JSON
{
        "_type": "waypoint",
        "desc": "Description",
        "lat": 49.241172,
        "lon": 5.806134,
        "rad": 25,
        "tst": 1650385174,
        "topic": "owntracks/user/fo/waypoints"
    }
```

**Comment by jpmens** [comment]
What you are showing there is the JSON of a waypoint as the device reports it to the server. What you wish to do is to create/define a new waypoint on the device which [can be done remotely](https://owntracks.org/booklet/features/remoteconfig/) with a slightly different JSON payload that can carry several waypoints/regions at once.

Note that Remote Commands must be enabled on the device settings.

**Comment by jpmens** [comment]
Did this work for you, @Tobstr02 ?

**Comment by jpmens** [comment]
Closing as answered and as stale.
