### ISSUE TITLE
Owntracks status in HA app device_tracker

### ISSUE THREAD

**Issue by AcidSleeper** [owntracks/talk#140]
Hello there.

Have a strange problem with my Owntracks in Home Assistant. Need help. The problem occured when both my son and wife changed phones: my son phone did a new installation and my wifes phone copied the old phone settings.

1. I have 3 phones (1 iphone, 2 android) connected to Owntracks in HA.
    - device_tracker.niclas_iphone_owntracks
    - device_tracker.sara_android_owntracks
    - device_tracker.gustav_mobilowntracks
    
2. I also have device_trackers from Home Assistant app.
    - device_tracker.niclas_iphone
    - device_tracker.sara_mobil
    - device_tracker.gustav_mobil

The problem is that either "device_tracker.gustav_mobilowntracks" is somehow sending message to "device_tracker.niclas_iphone" and "device_tracker.sara_mobil" with is name and status. OR HA app is getting that info somehow from device_tracker.gustav_mobilowntracks. The normal status of HA app device.tracker should be "Hemma" /Home in swedish/.
See picture.
![owntracks](https://user-images.githubusercontent.com/44057882/166159864-1e8be752-f2d6-428e-b8ca-a20c37752a93.jpg)

Se configfiles for owntracks on each device:
[Saraconfig.txt](https://github.com/owntracks/talk/files/8599518/Saraconfig.txt)
[Gustavconfig.txt](https://github.com/owntracks/talk/files/8599519/Gustavconfig.txt)
[Niclasconfig.txt](https://github.com/owntracks/talk/files/8599520/Niclasconfig.txt)

**Comment by jpmens** [comment]
A very brief glance at the *.txt files you’ve attached show differing types of specification for the deviceIds. That _might_ be a source of confusion? I would carefully check those to see that they correspond to the names you are expecting to get. It’s useful to remember OwnTracks apps use `owntracks/<username>/<devicename>` as topics to publish to, by default.

Other than that we can likely not help you with HomeAssistant; you’d have to ask that project, please.

**Comment by AcidSleeper** [comment]
Im not very familiar with owntracks. Could you be more specific about the difference between theese 3 mobiles? Maybe edit them så there is no fault from my side. =)

Should deviceId be the same for all 3 mobiles?

Thanks!

**Comment by jpmens** [comment]
We cannot give you specific configurations as we're not clear as to what you need. You will want to pay attention to how you've configured "username" and "deviceId" as those are part of what makes the address (topic) that the apps use to publish location data.

All three devices will want distinct combinations. For example I can have two devices "owntracks/jpmens/phone" and "owntracks/jpmens/otherphone", and another friend might well have "owntracks/susanne/nokia". Depending on how HomeAssistant is configured you will likely have to configure these topics there as well.

Good luck.

**Comment by AcidSleeper** [comment]
So the deviceId should be different or not?

**Comment by jpmens** [comment]
>So the deviceId should be different or not?

I _can_ be different, but need not be. The full topic (owntracks/username/devicename) must be unique across all your devices.

The topic must match what the server obtaining your location data expects it to be.

**Comment by AcidSleeper** [comment]
I have a problem with this.

Can someone more qualified check the configfiles and see of something is strange and/or wrong in configuration. 
and perhaps change the configfiles to a correct setting.

I know that perhaps this isnt an OwnTracks issue and a HA issue with OwnTracks. But have to start somewhere and check of any potential wrongdoings by me.

**Comment by ckrey** [comment]
the configs seem to be ok.
 
We do not have in depth knowledge of HA. 
But you should check in HA the 
- Persons
- the Devices you have linked to the Persons,
- Zones

**Comment by AcidSleeper** [comment]
Hey
I checked Zones and there is something strange.
![BE2CE5D1-A9F3-4606-BF06-8B06AE3A3396](https://user-images.githubusercontent.com/44057882/166517399-9f457287-be67-49a0-bdbd-de81afbf7ada.jpeg)

How could (if you know this) OwnTracks a zone!?
This is why Im getting strange behaviour. 

Whats the setting so Gustavs OwnTracks zone dont register in HA?
The othe mobiles dont register their zone in HA.

**Comment by AcidSleeper** [comment]
Seems like I found ONE solution. 

In HA settings there is a configuration thats called "waypoints:" - true or false. I had it to true but changed it to false. Also had to clear retained mqtt-messages.

But that doesnt explain why only 1 of 3 mobiles transfer their "zone" into HA. So it must be a setting in Owntracks on Gustavs mobile. But I cant find it.

**Comment by jpmens** [comment]
Have you been able to solve this on the HA side?

**Comment by AcidSleeper** [comment]
No. But set waypoints to false in above… havens had ANT problems since
