### ISSUE TITLE
Broader/'city level' location display

### ISSUE THREAD

**Issue by cr08** [owntracks/talk#141]
This would probably be aimed more for the existing web frontend available (https://github.com/owntracks/frontend) but curious if there's already an option or maybe it can be suggested here to have an inaccurate location display. Something city/region level, maybe a configurable radius that is randomly centered around your real location?

I'm looking at this from the perspective of how the public location sharing was with the old Google Latitude/G+ location services where it had the option of displaying a city level location publicly.

**Comment by jpmens** [comment]
We don't have that, but if you were meaning to share your location and "blurr" it, so to speak, this could be done programatically on the backend. Once the data is received it is distorted before adding it to some map or making it otherwise available.

**Comment by jpmens** [comment]
Closing as answered. Should you require more information, don't hesitate to ask.
