### ISSUE TITLE
Position confused by Cell Towers

### ISSUE THREAD

**Issue by peetwest** [owntracks/talk#144]
App build number: 2.4.9 (20409000)
Android version: 10
Device: Samsung Galaxy S9

I use Owntracks for tracking my route in a sailboat, and upload the track to Wordpress. It function very well expect one issue. 

It looks like Owntrack send wrong positions when I am near a Cell Tower. I have tried to find answers in the documentation but without luck. I use Owntrack on Android but guess the problem is the same with IOS. 

Please see the attached GPX file for understanding the issue.

**Comment by jpmens** [comment]
Note: I have edited your comment to remove the configuration which included your passwords.

**Comment by jpmens** [comment]
If you want to send us private data (your GPX file and/or your configuration) do so to support@owntracks.org please.

**Comment by peetwest** [comment]
@jpmens: Thanks. I send the files to Support:-)

**Comment by jpmens** [comment]
Re-opening as not yet completed.

**Comment by jpmens** [comment]
![rabbit-9291](https://user-images.githubusercontent.com/60706/176905858-fbcbab82-c35c-41db-aa99-3bcd55171afe.png)

Is this an example of what you mean by "wrong position", or did you actually land here?

**Comment by peetwest** [comment]
This is exactly what I mean. I am by boat and not on shore:-)

**Comment by peetwest** [comment]
Bonus info - If I use similar apps fx. TrackMe, with the same phone. I do not see this problem.

**Comment by linusg** [comment]
Note that the credentials are still visible through the edit history, so at the very least it's time for a new password. :)

**Comment by jpmens** [comment]
Thanks for reminding us, @linusg

**Comment by peetwest** [comment]
Password is changed!
Again - thanks for helping me when I am so stupid with my bad copy/paste operation:-)

**Comment by growse** [comment]
> Bonus info - If I use similar apps fx. TrackMe, with the same phone. I do not see this problem.

Are you using owntracks in "move mode"?

Can you check what value you have for "Ignore inaccurate locations" (in the advanced settings, or under `ignoreInaccurateLocations` in the config editor). I wonder if setting that to a lower value will filter out the non-GPS locations.

**Comment by peetwest** [comment]
Yes - I use Owntracks in "Move mode".

ignoreInaccurateLocations = 0

**Comment by growse** [comment]
> Yes - I use Owntracks in "Move mode".
> 
> ignoreInaccurateLocations = 0

Car you try setting this to a higher value? If you have this as 0, OT treats every location received from the device as 'publishable', regardless of how accurate it is. 

That point on land that you saw probably has an accuracy radius that includes your actual location, but is much larger (less accurate) than previous points.

**Comment by peetwest** [comment]
I have now tried to set ignoreInaccurateLocations = 100

The result is the same.

**Comment by peetwest** [comment]
important observation - the problem is only related to Android!

I have now tested OwnTracks on iPhone, Samsung phone and Lenovo tablet. The problem is only seen on Android - OwnTracks works perfectly on iPhone.

**Comment by jpmens** [comment]
We're tracking this with detecting inaccurate locations in Android; the feature should be in the next release which will be released as soon as it's ready.
