### ISSUE TITLE
Adress resolver disabled

### ISSUE THREAD

**Issue by FPPMvB** [owntracks/talk#145]
Sunce a few days I can no longer see the location name. Messag states: adress resolver disabled with GPS Locations.

How can this be fixed?

**Comment by jpmens** [comment]
Is this on iOS? Have you clicked on the folded-map icon on top left to enable reverse lookups?

**Comment by FPPMvB** [comment]
Hi Jan Piet,

Dank, dat was dus het probleem. Alles werkt weer!
Thxzzzz

Met vriendelijke Groeten,
Frank van Berkel

**Comment by jpmens** [comment]
Glad it works for you. Closing as solved.
