### ISSUE TITLE
How can I persist location data forever?

### ISSUE THREAD

**Issue by kprohith** [owntracks/talk#149]
I am utilizing the API to pull in data as JSON from the HTTP endpoint. But the data seems to be resetting every 24 hours. Is there anyway to ensure that the collected geo location data is persisted for all users so that when I fetch data using the API, I get access to the entire all time location history of the user?

**Comment by jpmens** [comment]
When you say "HTTP endpoint" I assume you mean the Recorder? If so, there is no such thing as "resetting every 24 hours". The Recorder stores data until you delete its files physically or until your disks run full, whichever occurs first. :-)

**Comment by kprohith** [comment]
I realised that I had to pass the "from" parameter to the API endpoint to retrieve data older than 24 hours. 
Thanks!

**Comment by jpmens** [comment]
Glad you found it.

On the server itself (i.e. on the machine on which Recorder is running) you can use `ocat(1)` to access the data, permissions assumed.
