### ISSUE TITLE
Where to find iOS setting for Location Publication Mode?

### ISSUE THREAD

**Issue by devodl** [owntracks/talk#15]
My experience has been that the Owntracks iOS app only publishes location to my MQTT Mosquitto server when I force a manual publish. I've read that setting a mode to "Significant Location Change" would publish the location when the user moves 500 meters withing 5 minutes which would meet my needs. 

In the OwnTracks Booklet under Docs >> Features >> Location >> iOS it states:
> The iOS app offers 3 modes of location publication:
>  - Quiet mode
>  - Manual mode
>  - Significant location change mode
>  - Move mode
I've looked in both iOS > Settings > General > Privacy > Location Services as well as in OwnTracks > Settings and cannot find any setting screen for _Location publication modes_.

Could someone please provide excrutiatingly detailed instructions (or maybe even a screen shot) for how to find and set Location Publication mode?
I want to set Location Publication Mode to: Significant Location Change  but cannot find any place to set it.

Thanks!
Steve

**Comment by ckrey** [comment]
Thanks Steve, we will work on the documentation with more screenshots.

The `monitoring`mode in iOS can be controlled either by sending a [configuration](http://owntracks.org/booklet/tech/json/#_typeconfiguration) to the device or via the UI:

The second button from the right in the navigation bar indicates and toggles the `monitoring` mode:

⏹ Quiet mode
⏸ Manual mode
▶️ Significant Changes mode
⏩ Move mode

![simulator screen shot 06 06 2017 07 31 58](https://cloud.githubusercontent.com/assets/4027289/26815250/818f51d4-4a8b-11e7-824e-de5948490568.png)

**Comment by devodl** [comment]
Christoph,
Thanks for the explanation (and a great app like OwnTracks).  That is one button I never thought to try and apparently the iPhone is already set for Significant Location Change which still leaves me with a problem.

On my Android phone OwnTracks reports/publishes my location changes as expected.
My wife's iPhone 6s is another story. In iOS Location Services has OwnTrack set to "Always" update but it seems to only publish a location when I manually force the publish.  A colleague at work has had the same experience with his daughter's iPhone.

I'll continue my analysis and see if I can get OwnTracks to reliably report when the location changes for an iPhone.

Thanks again.

**Comment by jpmens** [comment]
We've often seen people swipe out the app on iPhones; there's been an old-wives tale going around for years, and people believe that lowers RAM and/or CPU consumption on iPhones; all it does is absolutely zilch. Do you know whether your wife does that per chance? That would explain missing location updates.

**Comment by devodl** [comment]
It is highly unlikely that my wife is killing the app by swiping. 
I'm not sure she even knows she can do that.

I've been monitoring the mosquitto log and only see events from her iPhone when I manually publish. I'll try again tonight when I get home.

**Comment by devodl** [comment]
Solved!   
At first I didn't see the mode change button on the iPhone because it had a different shape than the "Play button" triangle shown above. Once I cycled through the modes (observing various button icons/shapes) I was able to set Significant Location Mode and now the iPhone reports/publishes to my mosquitto server.

Thanks!
