### ISSUE TITLE
Transition from Google Maps to Owntracks

### ISSUE THREAD

**Issue by maxime1992** [owntracks/talk#153]
Hello, thanks for the project! I haven't played with it yet but I'm in the installation steps! :smile: !

I know it's possible to export Google Maps data, is there any easy way to import the data in owntracks so that the transition is painless without any data loss?

**Comment by jpmens** [comment]
I wouldn't call it easy ... you'd have to get the data in such a form as that it's compatible with and recognized by our OwnTracks Recorder. I don't think anybody's done that yet, at least I'm not aware of appropriate programs with which to do that.
