### ISSUE TITLE
How is Owntrack frontend supposed to work?

### ISSUE THREAD

**Issue by maxime1992** [owntracks/talk#154]
Hello, I just setup my own instance of owntracks but I'm confused.

I'd have thought I'd have to create an account and do the same for as many guests I want on the server. But my frontend displays the map to everyone without any logging at all, is that normal? Am I missing some configuration? I'm not too blocked by this I guess I could just put it behind my Authelia but I feel like I'm missing someting.

Second question: How does one device should identify itself? As it's supposed to support multiple people and there seem to be no authentication, how can a device being identified? In the Android app, preferences/connection I've set it to HTTP, set my host, and I see there's an identification option but I don't understand what I'm supposed to put here? Is it just for MQTT? I'm using HTTP in my case so can I still use that section? If I put a user name and a password, is it going to create my user? What should I put in device ID and tracker ID?

Thanks, sorry for what seem to be stupid questions!

**Comment by jpmens** [comment]
About question 1: yes that is normal; Frontend doesn't implement AAA.

About question 2: a device is identified by <user>/<device>. The identification data you see in the Android app for HTTP is the auth that is sent to the backend, e.g. your OwnTracks endpoint (Web server). Users aren't "created", but it's the backend which permits or denies access to your apps and the credentials they use during authentication.

**Comment by jpmens** [comment]
Closing as answered, but feel free to report if you still have questions.
