### ISSUE TITLE
Owntracks and Year 2038 Problem

### ISSUE THREAD

**Issue by farahlima** [owntracks/talk#156]
As a personal project I'm building a backend solution for HTTP payloads in Golang using MariaDB as storage. 
While looking at the booklet I noticed that the "tst" field in the JSON paylaod says that the value is "UNIX epoch timestamp in seconds of the location fix" and this got me wondering if there would be any issues with the Year 2038 problem. Is this value passed as a 32bit or 64bit integer (i think that this question applies to both iOS and Android clients). Thanks

**Comment by linusg** [comment]
I did some digging:

- OwnTrack Android client: `long`, i.e. 64 bit.

  https://github.com/owntracks/android/blob/355caaa9c54773c0de3cf60b888e33914d4aef6d/project/app/src/main/java/org/owntracks/android/model/messages/MessageWaypoint.kt#L22-L23

- OwnTracks iOS client: `NSNumber` storing a double, i.e. 64 bit.

  https://github.com/owntracks/ios/blob/cb55c7d7878b51491a3787c9403076c837371489/OwnTracks/OwnTracks/OwnTracksAppDelegate.m#L1621

- OwnTracks recorder: C `long`, i.e. 64 bit (assuming a modern machine):

  https://github.com/owntracks/recorder/blob/37cae69f5fc0c369b1dad2e5071195d14251c2e1/storage.c#L656

- OwnTracks frontend: Using JS's `JSON.parse()`, so a 64 bit double as well.

Hope this helps!

**Comment by farahlima** [comment]
Wow, thank you so much. It helped a lot!
