### ISSUE TITLE
Q: why isn't "created_at" in every payload? 

### ISSUE THREAD

**Issue by na-am** [owntracks/talk#157]
hi,
i wonder why the payload doesn't have all the time "created_at" on location type:
{"_type":"location","acc":15,"alt":528,"batt":69,"bs":1,"cog":317,"conn":"m","inregions":["x814"],"inrids":["5eb246"],"lat":47.xx4518,"lon":8.xx2206,"m":2,"p":95.761,"tid":"NE","tst":1680598958,"vac":1,"vel":0}

that happens when i change manually the location interval on my iPhone

thx
na-am

**Comment by jpmens** [comment]
`created_at` identifies the time at which the message is constructed (vs. `tst` which is the timestamp of the GPS fix)

**Comment by na-am** [comment]
yes, i've a message/payload, but no created_at timestamp
do you see the point? lat+lon w/o a timestamp i've to ignore for my database

**Comment by jpmens** [comment]
what is the value of `"t"` at that moment?

**Comment by ckrey** [comment]
“created_at” is only created if the timestamp of the fix differs”

**Comment by jpmens** [comment]
Closing as answered
