### ISSUE TITLE
When my MQTT broker is offline

### ISSUE THREAD

**Issue by szac** [owntracks/talk#16]
Hi,

Will the device app still queue data to be published when the device is connected to the internet but MQTT broker is offline? 

I'm intending to create a mobile data logging server for my camper set up.  I'll have a dynamic dns configured, but occasionally the machine that the broker is running on will not be connected to the internet.  How will the Owntracks app handle the publishing of the data in this scenario? 

Thanks!

**Comment by jpmens** [comment]
If your MQTT broker isn't reacheable, our apps queue outgoing data hoping to deliver it as soon as the broker is available; in other words, you should be ok with what you want to accomplish, providing you're ot offline for more than a few days.

**Comment by szac** [comment]
Excellent.  Is the queue limit based on storage?

**Comment by jpmens** [comment]
The top of [this issue](https://github.com/owntracks/ios/issues/378) describes how we do it on iOS, and I think Android is similar.
