### ISSUE TITLE
Still active? Interview?

### ISSUE THREAD

**Issue by jp-bennett** [owntracks/talk#162]
Hey, this is a really neat idea. Is the project still active? And if so, would one or two of the devs be interested in chatting about it for a podcast (FLOSS Weekly)? Shoot us an email at floss[at]twit.tv.

In other news, I'm working on integrating location data from Meshtastic into Owntracks, which should be pretty nifty once it's working. Should make for a neat asset tracker that can work even without cellular connection.

**Comment by jpmens** [comment]
We are still active and certainly willing to talk. I’m off for a fortnight, so if nobody else raises a hand we’ll have to wait for a bit.

**Comment by TKone7** [comment]
Did that ever happen? Could not find the episode, would be very interested to listen 😉

**Comment by jp-bennett** [comment]
Not yet, but we'd still love to have a project member on the podcast. Floss at twit dot TV is the address to set it up.

**Comment by jp-bennett** [comment]
@jpmens Did you or another team member ever reach out to the twit email address mentioned above?

**Comment by jpmens** [comment]
@jp-bennett I am doing so right now.

**Comment by jpmens** [comment]
I'm [reading](https://hackaday.com/2024/01/17/floss-weekly-episode-766-webrtc-the-hack-that-connects-everyone-to-everything/#more-657056)

> we’re interviewing Jan-Piet Mens of the OwnTracks project!

This will be recorded on Wednesday, January 24th 2024, beginning at 17:30 UTC.

:-)

**Comment by jpmens** [comment]
The [show was recorded and is available now](https://hackaday.com/2024/01/24/floss-weekly-episode-767-owntracks-are-we-there-yet/).
