### ISSUE TITLE
Import tracks etc from an SQL db 

### ISSUE THREAD

**Issue by ippocratis** [owntracks/talk#163]
Been using traccar with a mariadb database for some time and before that google
I've seen the google takeout script and the pull request that brings it up to date
but
Is there any script that can import tracks to owntracks from an SQL dump?

**Comment by jpmens** [comment]
>Is there any script that can import tracks to owntracks from an SQL dump?

I'm not aware of any generic import script as it will strongly depend on the database schema.

**Comment by ippocratis** [comment]
> >Is there any script that can import tracks to owntracks from an SQL dump?
> 
> I'm not aware of any generic import script as it will strongly depend on the database schema.
> 

Sory if I was not clear
what exist is a script to import from google take out
But I've been using traccar for quite some time with Mariadb
I was wondering if there was any tool to import to recorder from sql

**Comment by jpmens** [comment]
>I was wondering if there was any tool to import to recorder from sql

I am not aware of such a tool.

(We use Traccar quite extensively and have actually contributed the OwnTracks connector for it to have OwnTracks devices submit their data to Traccar; the reverse is not something we've done so far.)
