### ISSUE TITLE
speed reported is zero if location interval is increased

### ISSUE THREAD

**Issue by captain-igloo** [owntracks/talk#167]
I am interested in using owntracks to report speed.  I am using owntracks/android and the OSS build.  I have found that if I increase the location interval, the speed reported is often zero (when I am moving).  If I set the location interval to say 10 seconds it works fine, but increasing it 30 seconds or more causes the problem.  Can anyone explain this?  

I can see that multiple locations would be needed to calculate the speed but I don't see why it shouldn't work with an interval of 30 seconds.

Thanks.

**Comment by jpmens** [comment]
You should be seeing velocity (`vel`) in the JSON reported by our apps.
