### ISSUE TITLE
OwnTracks for residency tracking?

### ISSUE THREAD

**Issue by yobyot** [owntracks/talk#169]
I have a newbie question: Could I use OwnTracks to create a diary of locations for a single iPhone?

I need to track residency across a period of a year. 

I'm happy -- eager, actually -- to set up a private MQTT broker and use OwnTracks as a data source because commercial  residency trackers just collect too much data for my comfort. Despite their promises of privacy, I suspect they cannot resist selling all that juicy location data to data brokers. And sorry, I just can't live with that kind of privacy invasion.

The OwnTracks project looks great and offers amazing functionality. But I didn't see a direct match for residency location storing and reporting in the Booklet.

**Comment by jpmens** [comment]
I'm not quite sure what you mean by 'residency tracking'.

With OwnTracks you would track your location (over a year or longer; you decide for how long you wish to store data using, say, our Recorder), and that will include the locations of residence you will be at.

If you _only_ wish to track the moments during which you are at particular locations, but not the route there-to/from, then OwnTracks is probably not the utility you wish to use, unless you are happy to use the apps in what we call "Quiet" mode and click on a button whenever you wish a location recorded.

**Comment by yobyot** [comment]
Thanks for the quick reply.

"Residency tracking" is the ability to produce a record for tax authorities of how many days were spent in a state or country.

Here in the US, is most states you need to prove you did *not* spend more than 183 days in them if you do not want to be taxed there. High-tax states are prone to demand proof that you were elsewhere if you are audited for tax purposes. (Absence isn't enough, BTW, you need to prove you actually have a life out of that state -- like a driver's license, _etc._)

As long as I could use the data to produce something simple, like a .csv containing the date and the location, OwnTracks would work for me. Quiet mode sounds perfect.

I wanted to find out if this could be adapted to my requirements before I started working with it to save time. Now, I'm looking forward to learning about MQTT and OwnTracks.

**Comment by jpmens** [comment]
Technically it would be possible to use OwnTracks to collect the data you ask for, however I cannot imagine it would satisfy legal requirements, as there's no way to prove you did not actually manipulate the data our apps collect.

OwnTracks' data is typically stored in our Recorder in flat files which can easily be modified by someone savvy or by someone who reads our documentation. :) 

So while you'd certainly be able to produce a list of dates and locations, nothing says to the authorities you didn't "invent" said data.

**Comment by yobyot** [comment]
All the commercial residency tracking apps basically use GPS location data to produce a log of location by date. 

So, the data source is the same. And the objective isn’t to produce a legal document but to have records — a diary — that can be used with other facts to as part of a response to a taxing authority. 

Thanks.

**Comment by jpmens** [comment]
In which case  you should definitely give OwnTracks a spin.
