### ISSUE TITLE
Priority between beacons

### ISSUE THREAD

**Issue by roqvist** [owntracks/talk#17]
I have multiple beacons set up in my home, on two different floor planes and both inside and outdoors.

In some rooms I have overlapping signals from two or more beacons. I can see that the beacon in the room typically has better signal strength, still from time to time some other beacon seem to take priority and is pushed as my current location.

Will Owntracks look at the signal strength when multiple beacons are in range to determine the current zone, or is it using some other criteria? Is there any way to set priority for beacons so that if both beaconX and beaconY are active go with beaconX?

In a perfect world the signal strength of all my beacons would be individually calibrated so the signal stays somewhat inside the room it's in, I've tried this to some extent but it's very difficult to adjust this vertically between floor levels (old wooden house, signal goes through floor easily) and some of my beacons are Raspberry Pi's (where the signal strength cannot be set).

**Comment by chbardel** [comment]
Also interested in this information! Is it somewhat related to the radius or does that only apply to the geofence?

**Comment by jpmens** [comment]
Sorry this issue was forgotten somehow....

Are you guys asking for iOS? If so I'll move this to iOS.

If you are asking about Android, please be advised that we've ripped out Beacon support in our Android app because it was wobbly at best and the APIs were unsatisfactory.

**Comment by chbardel** [comment]
I was asking about Android, don't know about roqvist.

**Comment by roqvist** [comment]
I'm using iOS, but it would be strange if the beacon priority differed based on OS.

Seems this has become slightly better in newer versions.

**Comment by ckrey** [comment]
Beacons are currently not supported in the Android version of OwnTracks.

The iOS app relies completely on iOS to detect iBeacons. The detection cannot be parameterized other than by specifiying the UUID, major and minor indentifiers.

We had similar experiences with Raspberry Pi driven iBeacons and wooden houses.

You may switch on "ranging", which triggers detailed beacon information including rssi to be published:

- https://owntracks.org/booklet/features/beacons/
 -https://owntracks.org/booklet/tech/json/#_typebeacon

**Comment by roqvist** [comment]
Thanks, I did not know about the ranging feature.
