### ISSUE TITLE
Websocket flag in configuration

### ISSUE THREAD

**Issue by Schlepptop** [owntracks/talk#170]
As far as I can tell, both the iOS and Android clients support using MQTT via Websocket.
However, the documentation does not specify a way to enable this mode of operation via a config flag in the .otrc file.
Am I missing something?

**Comment by ckrey** [comment]
you are right, it is not mentioned in the docs. 
We will add it there. But the flag exists: e.g. `  "ws" : false`

**Comment by Schlepptop** [comment]
I see, thanks for the clarification!
