### ISSUE TITLE
Support for Importing .KML for setting up waypoints

### ISSUE THREAD

**Issue by DjAnu** [owntracks/talk#173]
Hi, I saw on ideas page you mentioned kml support is enabled in backend. Wondering if it's possible to define complex  or simple polygon geofences using kml ? I am currently using the following app to get triggers based on owntracks tracker defined in the app so I can set polygon geofences. It would be great if I can define a polygon waypoint in owntracks itself.

In case you are wondering of the use case for polygon geofence. I mentioned it here : 

https://community.hubitat.com/t/request-app-driver-for-garage-door-automation-based-on-teslas-location/126453/2

In order for me to get false enter/exit alarms due to location of my house being close to the main street, I have to set up a polygon geofence.

Thanks.

**Comment by jpmens** [comment]
I don’t think we have support for KML and polygon geofences, anywhere in either the OwnTracks apps (android or iOS), nor on the Recorder backend.
Apologies if something raised your hopes. I know we have spoken about polygons before, but we never really dug deeply into that topic.

**Comment by DjAnu** [comment]
First of all, Thanks a lot for your quick response. There is hope right there :-).
I saw mention of kml export here : 

![image](https://github.com/owntracks/talk/assets/5419410/ef1049a9-0dc0-4024-950b-737e72b859e3)

Anyways, do you think this can be implemented/achieved. For peoples in the situation like me where a simple circular geofence isn't an option and homekit/life360 having min rad already set doesn't help either ?

**Comment by jpmens** [comment]
“Implemented in backend” (there might be a misplaced comma) refers to the gpx export our ocat utility can generate.

**Comment by jpmens** [comment]
> do you think this can be implemented

Surely. The question is how much effort it would be.

**Comment by DjAnu** [comment]
Alright, then how do I convince you to make it work :-). Sorry I am a Non-IT user otherwise I would have loved to work on it. But I can surely offer being a tester as needed

**Comment by ckrey** [comment]
In iOS, the operating system supports "circular" regions (waypoints) only. The OwnTracks app relies on the operating system feature with regards to regions.

**Comment by jpmens** [comment]
That’s a knockout criterion right there, as we couldn’t even attempt to be feature-compatible on the devices.
