### ISSUE TITLE
SOS button 

### ISSUE THREAD

**Issue by Evangelos360** [owntracks/talk#175]
It would be great if we had the option to issue an “alert” or “SOS” type of message from owntracks. This is a functionality that many similar asset tracking apps have, i.e. to alert their circle in case of an emergency or any other critical situation. 
Luckily this is something that can be easily achieved but requires a small code adaptation on both the android and iOS apps: 
The OwnTracks app has a “publish now” button on the top right of the app GUI as per the image below. When this button is pressed a manual json message is issued. The adaptation required is that a special identifier shall be added to the json message when we press this button. For example, “sos”. The applications receiving this message will know then that it was a manually issued “SOS”. 
What we do with this message depends on the required functionality. For example, we can use it to turn red the icon showing the contact that issued the alert on the web GUI. 
This is an easy adaptation and adds a new and valuable feature, for many of us I think. Please consider it for the next release. 
Thanks
Evan 

![publish_now](https://github.com/owntracks/talk/assets/60761286/89ab73a3-c794-4ee8-b99f-bb2cb1286515)

**Comment by jpmens** [comment]
In iOS this is already possible by either tagging a location publish or submitting a POI during [location publish](https://owntracks.org/booklet/features/location/#tags-and-poi), and in terms of feature parity the function will be available in our Android version as well when it's ready.

> This is an easy adaptation and adds a new and valuable feature, for many of us I think

I really wonder how many "many of us" are. ;-)

**Comment by Evangelos360** [comment]
Great feedback jpmens, I was not aware of this option on iOS as I’m an Android user. The purpose of the “SOS” feature is to easily (and rapidly) send such an alert message. Think of a car accident where you need to press a button on the app GUI front end. Or any other situation where you don’t have the time of configuring a message before you send it.  One of the popular features of Life360 is its SOS function on its GUI where users can easily access it to send this alert. So, I was thinking along these lines when I made this suggestion.

**Comment by jpmens** [comment]
> Think of a car accident where you need to press a button on the app GUI front end

I quite agree, and furthermore, I would hate for the pressing of a button in OwnTracks to cause an MQTT publish or an HTTP POST to get stuck somewhere... 

I'm not a fan of calling this an "SOS button"; I'd hate for us to raise expectations we cannot guarantee.

**Comment by Evangelos360** [comment]
I agree with you. Maybe SOS is not the best name for such a button/function. Maybe we dont even need to give it a name but simply add i.e. an identifier on the json message so we know that this came as a manual button press. Then the client application will have a means of differentiating it from the "standard" periodic location messages. If users want to use it as an SOS then or any other function for their client applications, its up to their discretion.

**Comment by jpmens** [comment]
>Maybe we dont even need to give it a name but simply add i.e. an identifier on the json message

location publishes which are submitted manually have a "t": "m" element in their JSON.

**Comment by Evangelos360** [comment]
Great! That's what i was looking for!

**Comment by jpmens** [comment]
Closing as answered.
