### ISSUE TITLE
Home Assistant is not showing location from iOS

### ISSUE THREAD

**Issue by jeppper** [owntracks/talk#18]
Hi
I have installed OT but it never updates its position unless i force an update on the map.
I want to get a notification in Home Assistant through MQTT. The conenction is okay.
I have created a home region and set manual mode as described in the manual but I get no notification when leaving/entering this zone.
What is wrong?

**Comment by jpmens** [comment]
You might mistakenly have paused OwnTracks on iOS. On the top right, second from right is an icon. When you click it it changes to the next "mode". The mode you're looking for is called "significant changes" and its icon looks like a play button. Please verify that you have that mode on.

**Comment by jeppper** [comment]
I have used the manual mode (pause symbol) because the documentation says that region events gets published when using this mode. 
I have tried sigificant changes too but it still does not update when entering og leaving my home region.

**Comment by jpmens** [comment]
What's the radius of your region? My experience shows that around 100m triggers fine, if you move out enough; please do not expect meter-type precision when using smartphones -- it's just not there; the OS doesn't give us that type of precision.

**Comment by jeppper** [comment]
the radius for home is 100m. I do not expect accuracy at all. I just want an update when I leave/enter home roughly. Today I am 30km from home but position was first updated when doing so manually.
I guess that the app can run in the background and still update through MQTT?

**Comment by jpmens** [comment]
Oh yes, absolutely: we do this all the time, literally, however I do confess I run iPhones in _significant mode_ only, so it might be you've uncovered a bug.

Can you please set to significant changes and see what happens when you next approach your geo-fence? 

As to your question: iOS apps are put to sleep by the OS. Periodically we're allowed to "wake up" for a few seconds. What we then do is send off a _ping_ via MQTT (you can identify payloads of this type containing a `"t" : "p"` in them), and then we're put back to sleep. However, when iOS detects enter/leave of a geofence, we're woken up directly and do our thing which, in this case, will be publish a transition event to MQTT.

If that doesn't work, we're going to have to delve a bit deeper. Please give us iPhone model, iOS version. I'll assume you're using latest OwnTracks version from the app store.

**Comment by jeppper** [comment]
I have tried to set it to significant changes but I will do it again see what happens when entering/leaving the region the next few times.
It is an iPhone 6 with iOS 10.3.2 and using version 9.5.9

**Comment by jeppper** [comment]
I have tried the significant mode since yesterday and I can see that it seems to update its position when I look at the map of the owntracks app and also the map of Home Assistant but no notification until I manually publish from the map of owntracks??

**Comment by jpmens** [comment]
Can you please show us broker (Mosquito?) logs of the pertinent times you think the message ought to have been published? (You can send them to support@owntracks.org if they contain sensitive information.)

**Comment by jeppper** [comment]
I will look into how to obtain these logs.
Do you know if I have to use/export the Regions created in owntracks in Home Assistant or should this not be necassary?

**Comment by jpmens** [comment]
I can't quite parse your question.

We are talking OwnTracks all the time I hope? You have a region set up in OwnTracks, and you're expecting that to publish a transition event when you enter/leave that region. Irrespective of what Home Assistant is doing or wants, you need to determine whether that is happening.

For that, you have to connect (e.g. with `mosquitto_sub`) to your MQTT broker to check incoming messages from your OwnTracks app. Only when you know and understand what data is coming from where at which point, will you be able to continue and debug the rest of your setup.

Hence my request for logs; I had assumed you're checking with `mosquitto_sub` to your broker to see whether publishes are incoming.

**Comment by jeppper** [comment]
I am no Expert at all in MQTT i admit. I have only observed my device tracker status within HA which I guess should show if incomming messages from OT are received. When I manually publish my position from OT it IS updated in HA.

**Comment by jpmens** [comment]
There's no need to be an expert and "guessing" what'll happen isn't going to help you at all. We have tried to document what OwnTracks does and how you can see what it is doing in [our Booklet](http://owntracks.org/booklet/). If you find it's lacking, either contribute to it or tell us what is missing, and we'll gladly try to improve on it.

In short, my well-meant advice: you can't do home automation of any kind until you know what your stuff is doing.

**Comment by jeppper** [comment]
I will try to get the logs and then return :-)

**Comment by ckrey** [comment]
Please show us how you defined the region:

![from skitch](https://user-images.githubusercontent.com/4027289/27992783-26f2c7bc-649c-11e7-91f8-3bb00ef763b7.png)

**Comment by ckrey** [comment]
Then check if you see Enter/Leave notifications in iOS Notification center:

![from skitch](https://user-images.githubusercontent.com/4027289/27992787-435ea754-649c-11e7-88db-9e5e341a9c15.png)

**Comment by jeppper** [comment]
I have the region defined exactly like that and I also get the iOS notification as above. I have just tried to exit and enter my home region.

**Comment by jeppper** [comment]
I have now the logs.
This morning at about 6.26 I got a message in the notification center that I left home and I can see in the Logs that my phone connects to mosquitto at that time too.
Anyhow my Home Assistant does not update its position unless I publish it manually.

1499734796: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499736597: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499738398: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499740199: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499740939: New connection from xxx.xxx.xxx.xxx on port 1883.
1499742000: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499743801: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499745602: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499747191: New connection from xxx.xxx.xxx.xxx on port 1883.
1499747192: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499747252: New connection from xxx.xxx.xxx.xxx on port 1883.
1499747252: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499747391: New connection from xxx.xxx.xxx.xxx on port 1883.
1499747391: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499747403: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499747575: New connection from xxx.xxx.xxx.xxx on port 1883.
1499747575: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499748161: New connection from xxx.xxx.xxx.xxx on port 1883.
1499748161: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499748250: Client jesperJEMiPhone has exceeded timeout, disconnecting.
1499748815: New connection from xxx.xxx.xxx.xxx on port 1883.
1499748815: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499749204: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499749250: New connection from xxx.xxx.xxx.xxx on port 1883.
1499749250: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499750695: New connection from xxx.xxx.xxx.xxx on port 1883.
1499750695: New client connected from xxx.xxx.xxx.xxx as jesperJEMiPhone (c1, k60, ujesper).
1499751005: Saving in-memory database to /var/lib/mosquitto/mosquitto.db.
1499752460: New connection from xxx.xxx.xxx.xxx on port 1883.
1499752460: New client connected from 1

**Comment by jpmens** [comment]
Now show us your Mosquitto ACL please.

**Comment by jpmens** [comment]
Also, please enable Mosquitto debug logging so that we see connection codes

**Comment by jpmens** [comment]
@jeppper you've also not demonstrated that the app is at all at fault: we asked you to

> For that, you have to connect (e.g. with mosquitto_sub) to your MQTT broker to check incoming messages from your OwnTracks app.

please show the pertinent messages (whereby you may obviously obfuscate the lat/lon)

**Comment by jeppper** [comment]
The observations below was made with mosquitto_sub

This seems to be cyclical
Client mosqsub/27958-hassbian received PUBLISH (d0, q0, r0, m0, 'owntracks/jesper/JEMiPhone', ... (34 bytes))
owntracks/jesper/JEMiPhone {"tst":"1499833775","_type":"lwt"}

I excited the home region and got an iOS notification about it, returned again and got a new notification. 
With mosquitto_sub anyway nothing happened during that time. The message below first showed when i manually published the position in the OT app.

Client mosqsub/28490-hassbian received PUBLISH (d0, q0, r0, m0, 'owntracks/jesper/JEMiPhone', ... (152 bytes))
owntracks/jesper/JEMiPhone {"t":"u","tst":1499887062,"acc":65,"_type":"location","alt":15,"lon":xx.xxxxxxxxx,"vac":10,"lat":xx.xxxxxxxxxxx,"batt":85,"conn":"w","tid":"JM"}


I still need to find the path on my Pi to the config file for enabling debug log and the ACL file

**Comment by jeppper** [comment]
Hi 
I have this from the log. I left home region at about 07.49 and also got a notificationfrom OT 07.49.
I did not get any update in Home Assistant.
PS: I can not find any ACL file on the PI

1500702548: Sending PINGRESP to DVES_E9CA17
1500702549: Received PINGREQ from ESPClient1
1500702549: Sending PINGRESP to ESPClient1
1500702563: Received PINGREQ from DVES_E9CA17
1500702563: Sending PINGRESP to DVES_E9CA17
1500702564: Received PINGREQ from ESPClient1
1500702564: Sending PINGRESP to ESPClient1
1500702565: New connection from xx.xx.xx.xx. on port 1883.
1500702566: New client connected from xx.xx.xx.xx as jesperjemiphone (c1, k60, ujesper).
1500702566: Sending CONNACK to jesperjemiphone (0)
1500702567: Received SUBSCRIBE from jesperjemiphone
1500702567: 	owntracks/+/+ (QoS 0)
1500702567: Sending SUBACK to jesperjemiphone
1500702567: Received SUBSCRIBE from jesperjemiphone
1500702567: 	owntracks/+/+/event (QoS 0)
1500702567: Sending SUBACK to jesperjemiphone
1500702567: Received SUBSCRIBE from jesperjemiphone
1500702567: 	owntracks/+/+/info (QoS 0)
1500702567: Sending SUBACK to jesperjemiphone
1500702567: Received SUBSCRIBE from jesperjemiphone
1500702567: 	owntracks/jesper/jemiphone/cmd (QoS 0)
1500702567: Sending SUBACK to jesperjemiphone
1500702578: Received PINGREQ from DVES_E9CA17
1500702578: Sending PINGRESP to DVES_E9CA17
1500702579: Received PINGREQ from ESPClient1
1500702579: Sending PINGRESP to ESPClient1
1500702581: Received DISCONNECT from jesperjemiphone
1500702593: Received PINGREQ from DVES_E9CA17
1500702593: Sending PINGRESP to DVES_E9CA17
1500702593: Received PINGREQ from jL_Mho:rdm=aJBp=9d_@i_ib2ncwmsmN7S[o9UhnIeFcx=a8aG8Rva;0W^g;IKIP
1500702593: Sending PINGRESP to jL_Mho:rdm=aJBp=9d_@i_ib2ncwmsmN7S[o9UhnIeFcx=a8aG8Rva;0W^g;IKIP
1500702594: Received PINGREQ from ESPClient1
1500702594: Sending PINGRESP to ESPClient1
1500702608: Received PINGREQ from DVES_E9CA17
1500702608: Sending PINGRESP to DVES_E9CA17
1500702609: Received PINGREQ from ESPClient1
1500702609: Sending PINGRESP to ESPClient1
1500702609: New connection from xx.xx.xx.xx on port 1883.
1500702609: New client connected from xx.xx.xx.xx as jesperjemiphone (c1, k60, ujesper).
1500702609: Sending CONNACK to jesperjemiphone (0)
1500702610: Received SUBSCRIBE from jesperjemiphone
1500702610: 	owntracks/+/+ (QoS 0)
1500702610: Sending SUBACK to jesperjemiphone
1500702610: Received SUBSCRIBE from jesperjemiphone
1500702610: 	owntracks/+/+/event (QoS 0)
1500702610: Sending SUBACK to jesperjemiphone
1500702610: Received SUBSCRIBE from jesperjemiphone
1500702610: 	owntracks/+/+/info (QoS 0)
1500702610: Sending SUBACK to jesperjemiphone
1500702610: Received SUBSCRIBE from jesperjemiphone
1500702610: 	owntracks/jesper/jemiphone/cmd (QoS 0)
1500702610: Sending SUBACK to jesperjemiphone
1500702623: Received PINGREQ from DVES_E9CA17
1500702623: Sending PINGRESP to DVES_E9CA17
1500702624: Received PINGREQ from ESPClient1
1500702624: Sending PINGRESP to ESPClient1
1500702625: Received DISCONNECT from jesperjemiphone

**Comment by jpmens** [comment]
Please learn to format code/logs between lines of three backticks; reading your messages is very hard (I have now done this for you).

I'm seeing disconnects from your phone very quickly. Are you swiping out the OwnTracks app?

**Comment by jeppper** [comment]
thank you :-)
No I only exit the app by tapping the home button.
Anyhow I very often get a "You did disable background fetch" notification when reopening the app. 
Don´t know if it means anything in this matter but I have not disabled anything.

**Comment by ckrey** [comment]
If you disabled background fetch then OwnTracks cannot sent in background when not moving. Isn't this the problem you initially reported?

The check is done when the app does start initially (either after swiping it out or when iOS suspends it).

If it reports "You did disable background fetch" then background fetches (Hintergrundaktualisierung in German) are disabled either for all apps or for OwnTracks specifically. Please check your Settings

**Comment by jpmens** [comment]
(groans)

**Comment by jeppper** [comment]
If you mean the app background refresh function of iOS I have now enabled it for OT. 
Anyway I still first gets the location update in Home Assistant when publishing it manually in the OT app. The iOS notification of OT pops up fine though.

**Comment by jpmens** [comment]
We are losing a lot of interest in this topic, to be honest, and for hass we are completely desinterested. Show us proof of what is happening, as requested, and remove OwnTracks from your iPhone and re-install to ensure you get out-of-the-box defaults.

**Comment by ckrey** [comment]
We found a bug in the setup of the iOS app.
@jeppper would you follow the instructions I gave to your fellow user here: https://github.com/owntracks/ios/issues/472

**Comment by jeppper** [comment]
It seems to work now, after following your instructions :-)
(I have now also updated the app and it still works)
thanks.
