### ISSUE TITLE
Wake via FCM when location is viewed

### ISSUE THREAD

**Issue by AndreKR** [owntracks/talk#180]
Before I read the Booklet, how I expected OwnTracks to work is this: When one of my friends visits a web site or opens their own app to find my location the server sends a notification via FCM to my phone to wake up the app, the app tries to find out my location (possibly with a timeout, in case I'm deep inside a building), sends it to the server and goes back to sleep, or stays "live" as long as my friend is watching my position.

But that's not what this app is for, is it? It doesn't seem to track who is watching whom and neither does it support remote wakeup, correct?

**Comment by jpmens** [comment]
We support report location, but that’s not as fine as you’d expect it to be. Otherwise you’re right, that’s not what OwnTracks does.
