### ISSUE TITLE
Installation Error: TAKS [verify some requirements] Assertion failed

### ISSUE THREAD

**Issue by Takeshidude** [owntracks/talk#183]
Hello,

I am attempting to install owntracks by following the booklet instructions. Everything went well until I reached point 5 of the Lanching Quicksetp section.

When I run ~/quicksetup# sudo ./bootstrap.sh, here is what I see:

```
PLAY [OwnTracks Quick Setup]

TASK [Gathering Facts]
ok: [localhost]

TASK [system: template out sys.info]
changed: [localhost]

TASK [verify some requirements]
fatal: [localhost]: FAILED! => {
     "assertion": "ansible_distribution_release in [ 'bookworm', 'jammy, 'mantic' ]",
     "changed": false,
     "evaluated_to": false,
     "msg": Assertion failed"
}
```

How can I resolve this error?

**Comment by jpmens** [comment]
Which OS and version are you using?

**Comment by Takeshidude** [comment]
Well, I could have sworn I was running bookworm, but I am in fact running bullseye. I suppose we can chalk this up to an ID10T error then.

Thanks for the reality check lol

**Comment by jpmens** [comment]
>Thanks for the reality check lol

;-)

Good luck and let us know in a new ticket whether you encountered problems.
