### ISSUE TITLE
Garmin client for OwnTracks

### ISSUE THREAD

**Issue by b8fly** [owntracks/talk#185]
You asked for it...

<img width="727" alt="Bildschirmfoto 2024-06-11 um 17 10 27" src="https://github.com/owntracks/talk/assets/1789345/17d39b16-8d5f-4723-bea6-557f7891379e">

If you have a Garmin watch on your wrist and a mobile phone in your pocket, then you now also have an OwnTracks client!

https://apps.garmin.com/apps/d8bcd6d2-d7b8-456b-ae01-ba45bbe202cb
https://apps.garmin.com/apps/9130a1c5-3335-47c7-b6ee-c118c2bd20e4

Just wanted to let you know :)
Cheers

**Comment by jpmens** [comment]
😀

Really cute. Thanks for letting us know.
