### ISSUE TITLE
I already have an apache server running with SSL

### ISSUE THREAD

**Issue by Mega1024** [owntracks/talk#186]
I don't want to use MQTT - I want the client on my phone, and ONE server that receives the location updates directly from the phone app.

I don't want the "all in one" canned solution that requires I give root access to scripts I didn't write, and installs software outside of my existing package manager, and then wants to do its own SSL when I already have that setup for my webserver.

Are there any guides or existing projects for something standalone?

Perhaps in PHP, that will integrate with an existing apache install, at least to receiving and storing the data, even better if there was a UI for reviewing as well.

**Comment by ckrey** [comment]
Reading your unfriendly comment I am tempted to simply ask you to go away.

 We spent a lot of time and work making OwnTracks usable for a wide range of people with different levels of technical skills. This was the reason to create `quicksetup`.


If you want to read further you may use our recorder behind nginx or apache https://github.com/owntracks/recorder
or have a look at other backends. There is one PHP backend referenced here: https://owntracks.org/booklet/guide/clients/
We would appreciate hearing from you if you find a setup matching your needs.

**Comment by Mega1024** [comment]
Well I might as well just go away anyway, since both of the links you posted give 404 errors. No such pages exist.

**Comment by ckrey** [comment]
I corrected the links

**Comment by jpmens** [comment]
Closing this as user says they've gone away!
