### ISSUE TITLE
Recorder - Are there any plans of adding functionality to see points and Track of a specific day of the month and year?

### ISSUE THREAD

**Issue by QuantumOwl** [owntracks/talk#187]
I want to replace google maps "Your timeline" with this now that they disabled the option to use it from my PC, but cant figure out how to do the above (I may just be missing something). Can i currently do this? If not, is this planned for the future?

**Comment by jpmens** [comment]
This is possible with our [Frontend](https://github.com/owntracks/frontend)

**Comment by QuantumOwl** [comment]
I knew i was missing something. Thanks, ill install it.
________________________________
