### ISSUE TITLE
Question TLS VPS

### ISSUE THREAD

**Issue by iFabse** [owntracks/talk#192]
I want to install the owntracks service on my VPS Debian server. I have had set up an Apache Webserver with SSL encryption - certificates from my VPS provider.
Do I have to disable the Apache web server, and switch to nginx? How can I use the certificates from my VPS provider?

**Comment by jpmens** [comment]
We don't support using Quicksetup with an existing Apache installation. Theoretically it's possible to use existing certificates with Quicksetup, but we have no automation to enable this, so it'd be a lot of work -- not recommended.

That said, if you wish to install the individual components (Recorder, Frontend, Mosquitto) that is possible, but you would please have to study the instructions for the individual components.

**Comment by iFabse** [comment]
Ok, thanks for the response. I installed it know with the official debian 12 instructions and got it to work with my raspberry pi. I have to get more into it, because I want to use owntracks with https and not http. Although it didn't work good with https ... have to read more :)
