### ISSUE TITLE
Geofence question(s)

### ISSUE THREAD

**Issue by koymoy** [owntracks/talk#193]
May be an dumb question, but here goes: 

All settings in both android/iphone has been checked in regards of battery, app-sleeping, and location-policy. Tracking in the owntracks-app is set to significant changes

1. I use owntracks (or i trying to) in Athom Homey to get notified, when kids, wife, me enters or leave different fences, ie. home, work, school. So, i started by defining the different fences in Homey, and used that in the different flows. That didn't work. I then tried creating the fences on my phone, and they then show up in homey OT-app. They just only work for me. If i "re-use" the location/fence defined by me, for my kids "entity", i don't get any notification. If i define the same location/fence on each users phone(owntrack app), and use those in the Homey flows, it works. So long story short - is that the way its supposed to work, or am i missing something? it seems contra-intuitive to have 3-4 different names for the same location, fx home. 

2. there often is double notification. Fx my wife gets double notification that i've arrived at work, or sometimes, that i have arrived, left, arrived within few minutes. Is that due to some sensitivity/error margin setting in relation to the specific geofence? 

All settings in both android/iphone has been checked in regards of battery, app-sleeping, and location-policy. Tracking in the owntracks-app is set to significant changes 

Otherwise, it's a great app, and i really appreciate it, so thanks!

**Comment by jpmens** [comment]
I don't think we know what _Athom Homey_ is so will probably not be able to help, particularly as there's no mention here of which protocol is being  used.

Technically regions (waypoints, geofences) work quite well on our Android/iOS apps, so I might suggest you check with the _Athom Homey_ people.

**Comment by koymoy** [comment]
I'm sorry to presume it was common knowledge - my fault. It's a smarthome platform, and in that Ecosystem, theres an app, that connects the app on the phone with the smarthome hub. (https://homey.app/en-gb/app/nl.scanno.owntracks/Location-and-Presence/) and thus, making it possible to create different automations based on geofences. But thanks for replying.
