### ISSUE TITLE
How to set up OwnTracks for location sharing on a Raspberry Pi

### ISSUE THREAD

**Issue by nocluewhatido** [owntracks/talk#196]
Hello everyone,

I’ve spent the last two days trying to set up OwnTracks on my Raspberry Pi using Docker, but unfortunately, I haven’t been able to get it working.

The Pi is already running Pi-hole with Unbound and PiVPN, so a DNS is already linked to it. I followed the Quick Setup guide and tried various solutions with ChatGPT, but without success. While I could access the nginx website, that’s as far as I got.

Can anyone help me set up OwnTracks on the Pi, or does anyone know of a good guide for this specific setup?

**Comment by jpmens** [comment]
Our Quicksetup mechanism should get you what you need. http://owntracks.org/booklet/guide/quicksetupMessage ID: ***@***.***>

**Comment by nocluewhatido** [comment]
Hey @jpmens ,
Thank you for your reply. Did you mean the Quicksetup Guide? Your links is not working. I will try using the Quicksetup with docker.

**Comment by jpmens** [comment]
https://owntracks.org/booklet/guide/quicksetup/

Quicksetup isn't designed for docker but for bare metal setup, ie on your raspbi.

**Comment by jpmens** [comment]
Closing as answered.
