### ISSUE TITLE
If I have only 1 Windows PC, how can I set up Owntracks?

### ISSUE THREAD

**Issue by nhan000** [owntracks/talk#197]
I have a Windows 11 PC, and not very tech-savvy. My need, at its simplest form, is just to visualize my travel history. I don't even need to see it immediately with real-time update. Let's say after a 2-week trip, I can plug my phone to my PC, and transfer the location data to my PC, and visualize it then.

The first obstacle for me with the Quicksetup is the requirement of having a Linux device/VPS. Can I run a Linux VM only when I need to use OwnTracks? (When I want to transfer the location data to my PC, and when I want to visualize it.) If so I'd just run a Linux VM (I don't even know how to yet), and treat it as a Linux-capable device and just follow the guide? In the Intro section of the booklet, there's the mentioning of having a record of, but not sharing, my location data, but I don't think it's mentioned anywhere else in the booklet. Would that set up be easier?

Thanks a lot for your help!

**Comment by jpmens** [comment]
Quicksetup sets up the OwnTracks backend software on a Linux VPS, but this can also be a virtual machine (e.g. VirtualBox) running on your Windows PC. Do note that you might need to open ports in your router in order for Let's Encrypt (TCP port 80), MQTT (TCP port 8883) to access Linux in that VM on your Windows PC. There should be quite a bit of documentation on the Web on how to install VirtualBox on Windows and then Debian in that VirtualBox.

The OwnTracks apps want to transfer location data as it is obtained. While we do buffer data in case of network outages, etc. it is not intended to gather data for a long period of time and then transfer it on demand. If that really is what you want then OwnTracks will not be suitable.

**Comment by jpmens** [comment]
Closing as answered.
