### ISSUE TITLE
Waypoints android widget PR (#381)

### ISSUE THREAD

**Issue by nma83** [owntracks/talk#2]
Hi!

I had added this 'waypoints widget' to the android app way back in Jul 2016. During the course of its development in my local branch, the upstream moved to a new directory structure and refactored some of the code. Now, I am wondering if I should rebase and resolve all the conflicts and get some feedback on it. Does this widget sound like something the owntracks team would like to add to upstream?
https://github.com/owntracks/android/pull/381

Thanks!
NMA

**Comment by binarybucks** [comment]
Hi NMA, 

I'm sorry that your PR got ignored for so long. If possible, please update your PR. I will try not to introduce greater changes until you have updated it.

**Comment by nma83** [comment]
Thanks for the response Alexander. I need maybe a week or so to resolve conflicts and update the PR. Will post on the PR itself once done.

**Comment by nma83** [comment]
@binarybucks I am facing compile issues after the latest rebase. The upstream/master copy is building correctly for me, but with my changes on top of it, data-binding classes do not seem to be getting generated. Sample error:
```
error: cannot find symbol
import org.owntracks.android.BR;
```
I would need some help in figuring out what exactly is causing this failure. 
https://github.com/nma83/android/tree/waypoints_widget_rebase

**Comment by binarybucks** [comment]
If the databinding classes arent't generated, there is most likely an error in a layout XML file. Check the build log because between all the missing symbol errors the bad file is often logged.

**Comment by nma83** [comment]
I searched the errors for any XML issues, but the very first error (from a clean build) is this:
```
FusedContact.java:16: error: cannot find symbol
import org.owntracks.android.BR;
```
Reviewing my XML changes once more.

**Comment by nma83** [comment]
Still no luck finding the issue in XML. Are there any tools to help with debugging this?
