### ISSUE TITLE
New device for Owntracks based on SIM808 and Elecrow 32u4 A7

### ISSUE THREAD

**Issue by roblad** [owntracks/talk#20]
Hi,

There is a my proposal of device for Owntracks, it is prepared for standard JSON required by Owntracks

https://github.com/roblad/gpstracker

PS.

I am working on code for Elecrow board:

There will be accelerometer that will wake up device from deep sleep where power consumption will be ~5 mA max, that gives for 1500 mAh battery very long time of live.

32U4 with A7 (Al thinker)  GPS+GSM/GPRS Board is based on Mega32U4 and A7 GPS+GSM/GPRS module.

https://www.elecrow.com/wiki/index.php?title=32u4_with_A7_GPRS/GSM

http://www.jarzebski.pl/arduino/czujniki-i-sensory/3-osiowy-zyroskop-i-akcelerometr-mpu6050.html

It is almost ready 

I am looking for people that will able to create Windows Application that will change config.h and compile and upload through Averdue soft directly to the board.

https://www.elecrow.com/wiki/index.php?title=32u4_with_A7_GPRS/GSM

**Comment by jpmens** [comment]
Good stuff; and thank you for showing us. Do make sure to keep us updated in this issue, and when you're all done, we'd like to see a good photo! :-)

**Comment by roblad** [comment]
https://www.flickr.com/photos/128785919@N03/sets/72157683518223543

**Comment by roblad** [comment]
Hi,

I finished next device for Owntrack for  Elecrow 32u4 with A7 GPS/GPRS/GSM :-)


https://github.com/roblad/Owntrack_Elecrow_32u4_A7_GPS_GPRS_GSM_tracker/tree/master


Thanks,
RL

**Comment by vuongductuanktmt** [comment]
I use module 32u4 with A9G when run system get infomation GSM --> OK
but not get infomation GPS "Invalid GPS data"

**Comment by roblad** [comment]
Hi,

That was for A7 not A9 - probably some modyfication of code is needed. May be I will buy A9 module and I will recode that.
