### ISSUE TITLE
Looking for setup advice

### ISSUE THREAD

**Issue by cowgoesmoo69** [owntracks/talk#202]
Currently using google maps timeline for tracking my location history for work. I'm interested in other options, since I'd prefer to have control over my data, and found this project which looks very promising.

I have a VPS, which is currently hosting some websites using Plesk. I'm guessing I won't be able to use the quicksetup process, as from reading the guide it appears to be aimed at a VPS with nothing already running on it.

What is the best way to go about installing owntracks in this case?

**Comment by jpmens** [comment]
Ideally Quicksetup runs on a system without an installed Web server.

In case you don't wish to touch that, the individual parts (e.g. MQTT broker, OwnTracks Recorder, Frontend) will have to be installed separately, admittedly not necessarily something which is easy to do.

**Comment by cowgoesmoo69** [comment]
Thanks for your reply. I'm guessing it would be necessary to examine the Ansible playbook and follow the steps manually?

**Comment by jpmens** [comment]
It's not _necessary_ to do so, but if you can follow what the playbook is doing, you'll likely have the easiest setup experience other than actually running Quicksetup.

Now that you  mention it, you could actually get away with doing the Web portions (nginx) manually or differently, and leaving at least most of the remaining tasks as they are.

Do note though, please, other than maybe answering the odd question, I don't have time to hand-hold you along. I hope for your understanding.

**Comment by cowgoesmoo69** [comment]
No worries, I'll have a look through the playbook and see what's involved :)

**Comment by jpmens** [comment]
Closing as answered.
