### ISSUE TITLE
Cannot remove users from IOS or Android

### ISSUE THREAD

**Issue by zach-timms** [owntracks/talk#206]
Hi,

I mistakenly created 'duplicate' users with this command, running it twice with two incorrect [y] values:
`mosquitto_pub -t owntracks/[x]/[y]/info -f card.json -r -q 2`

These false users now show up (both on IOS and Android) persistently. I have tried:
`mosquitto_pub -t owntracks/[x]/[y] -r -n`
And this works, until the app is restarted. Then the false users show up again. Clearing them in the app doesn't work - they return after restarting.

I'm sure I'm missing something very simple, any help would be appreciated.
To be thorough I did a `find -name [y]` on the server, and deleted all instances and it is still occuring.

Thanks!
Zach

**Comment by jpmens** [comment]
You are clearing out `owntracks/x/y` and not `owntracks/x/y/info` which is where the CARD is. Try publishing a retained NULL to that topic, and the card will be removed as well, and all should be dandy.

In addition you might want to swipe the Friend out (swipe left).

**Comment by zach-timms** [comment]
You're a lifesaver, thank you! I was going mental. Hoping it was something simple like that 😁
Everything works as expected now

**Comment by jpmens** [comment]
Glad you got it solved.
