### ISSUE TITLE
MQTT Broker Error 61

### ISSUE THREAD

**Issue by chop249** [owntracks/talk#207]
Can anyone help with the MQTT Broker? I had it set up and running fine for months now. Out of the blue earlier in the week it stopped working and I get:

idle NSPOSIXErrorDomain 61 The operation couldn’t be completed. Connection refused {
    "_kCFStreamErrorCodeKey" = 61;
    "_kCFStreamErrorDomainKey" = 1;
}

Nothing on the broker or anywhere else changed, same port, port still forwarded, not using web sockets or TLS. If I reboot the broker it works for about an hour then goes back to not working. It is built on a Debian Bookworm LXC in ProxMox. Made sure everything was updated as well.

**Comment by jpmens** [comment]
I see `Connection refused` there which means either the broker is not listening on the desired port, or some firewall is preventing the connection.

**Comment by jpmens** [comment]
And for the record: a question such as 

> Can anyone help with the MQTT Broker?

is pretty thin in information.
