### ISSUE TITLE
Rather than using a phone, can I use a rPi in a fixed installation?

### ISSUE THREAD

**Issue by M-ax-G** [owntracks/talk#23]
Can I use owntracks on a Raspberry Pi as a fixed installation in a car?
I currently use OwnTracks on iOS, but rather than starting the app, putting it on the dash (where it falls off every now and then) I was wondering, whether there is something that runs on micro-controller (arduino, etc) or a rPi, which sends these messages to my broker at home? -> a Foxed installation in the trunk, GPS antenna on roof or so, boots up with ignition on, and sends its location.

**Comment by jpmens** [comment]
That's certainly possible if you're willing to invest time/work. [We've done crazy stuff before](http://jpmens.net/2016/04/16/a-tiny-esp8266-based-gps-tracker/).

**Comment by M-ax-G** [comment]
:) Thanks for the quick reply... this is a good start... I am interested in GPS to GSM send message OT-recorder understands... not relying on WiFi tethering etc. -- simply autonomous. I reckon I have to read a bit, how to connect the components to an Arduino and how to from the message. IS there code I can snatch (for the message build)?

**Comment by jpmens** [comment]
You'll find plenty of Python examples in our repositories. Also, I recommend `gpsd` to obtain GPS from a USB thing.
