### ISSUE TITLE
Windows app initiatives?

### ISSUE THREAD

**Issue by dnperfors** [owntracks/talk#24]
I was wondering if there are any plans or initiatives for a windows app? I would like to use owntracks in combination with home assistant, but I only have a windows phone and not android or ios.

**Comment by jpmens** [comment]
Definitely no plans for a Windows app. Does Windows phone exist anymore at all? I mean as in "it ain't a dead product"? ;)

**Comment by dnperfors** [comment]
I can understand your point of view. Good to know there is nothing planned from your side.
I did a little extra searching and found [MQTTLocationTracker](https://github.com/jeroenterheerdt/MQTTLocationTracker/), which is compatible with owntracks api. Although it only supports a basic location message, it seems enough for me to start with.

**Comment by jpmens** [comment]
I'm glad you found something suitable. Do test it, please, and we'd like to hear whether it works; it may be interesting to others with such a platform.
