### ISSUE TITLE
iOS app doesn't have access to location services following 9.7.1

### ISSUE THREAD

**Issue by reichley** [owntracks/talk#26]
I noticed the location arrow transformed to spinning wheel and never located my iPhone 7 on the map. After digging into the location services settings I noticed only the "never option." Clicked to select and backed out of settings. Now all three options (never, when using app, always) were available. Selected always. Killed app, rebooted iPhone, still showing 0,0 as coordinates and doesn't resolve location in app on map. 
![015fd651-d933-4719-b499-b38ce61c19ff](https://user-images.githubusercontent.com/8618579/31033164-1376dcba-a52d-11e7-93f0-05851b90a7a7.png)
![645356d0-2903-412e-adc1-9bfab8d3dc1f](https://user-images.githubusercontent.com/8618579/31033165-138fc5b8-a52d-11e7-94ee-1b26580ed180.png)

**Comment by jpmens** [comment]
I can reproduce this with 9.7.1. Thank you for your report. (Next time we'd appreciate issues reported for iOS in the iOS tracker, for Android in the Android tracker.)

**Comment by reichley** [comment]
You're welcome. 10-4 on posting to the appropriate tracker next time, sir.

**Comment by jpmens** [comment]
This problem is being tracked [here](https://github.com/owntracks/ios/issues/483#issuecomment-333290988), so I will now close this.
