### ISSUE TITLE
Latest version on iOS no gps

### ISSUE THREAD

**Issue by veames** [owntracks/talk#27]
Just updated to 9.7.1 on iOS 11 and gps does not seem to work. If I select the direction arrow I just get a spinning wheel.

**Comment by chrisboer** [comment]
You can put privacy and location on and off a day.enable.for.owntracks but after some.time the location is not set for owntracks again

**Comment by chrisboer** [comment]
So currently not really a.good work around

**Comment by juan11perez** [comment]
Same problem. No GPS.
Direction arrow keeps spinning

**Comment by ckrey** [comment]
The fixed version is @Apple for review. This usually takes less than a day, but over the weekend we may need a bit more patience

Von: iTunes Store <no_reply@email.apple.com>
Datum: 30. September 2017 um 15:25:10 MESZ
An: c@ckrey.de
Betreff: Your app (iOS) status is Waiting For Review

**Comment by chrisboer** [comment]
@ckrey if you want I can be a tester for your apple IOS app in TestFlight for the future I use owntracks for geofences as well as iBeacons and in combination with a private MQTT server. So quite some functionality

**Comment by ckrey** [comment]
@chrisboer you are now on the list of our external testers

We usually test

a) by developer
b) internally with a few users
c) with our external testers

before releasing to the public on the app store.

step c) requires approval of the build by Apple and we sometimes skip this step if it is an urgent fix

**Comment by TonyFeestneus** [comment]
It does work now with the update. But there is an issue: when using Http, if you go in to a zone where data signal is bad, it cant publish location, states http error 500 and does not recover from this.
Even at home on wifi it keeps giving http error. Would you change the settings completely it will work again, but that is not a viable workaround.

**Comment by ckrey** [comment]
@TonyFeestneus please don't reuse an issue for a different new issue!

HTTP error 500 is originated at the server, not the client. If I were you, I would take a look at my server.
The client retries to send it's data until it receives a positive return (HTTP 200-299).
