### ISSUE TITLE
HTTP error when no signal, does not retry correct

### ISSUE THREAD

**Issue by TonyFeestneus** [owntracks/talk#28]
When using Http, if you go in to a zone where data signal is bad, it can't publish location, states http error 500 and does not recover from this.

Even at home on wifi it keeps giving http error. Would you change the settings completely it will work again, but that is not a viable workaround.

HTTP server is always reachable, but it keeps saying error 500. Which is incorrect.

**Comment by jpmens** [comment]
Please open this issue in either our Android or our iOS issue tracker. The addresses are clearly stated in the README of this repository.

**Comment by TonyFeestneus** [comment]
my bad
