### ISSUE TITLE
What happened to https://community.owntracks.org ?

### ISSUE THREAD

**Issue by kylejohnson** [owntracks/talk#3]
I'm trying to track down a bug that my Wife's iPhone is hitting.  That lead me to https://github.com/owntracks/ios/issues/408, which leads me to https://community.owntracks.org/topic/110/intermittent-connection-issues-error-9829-in-ios-client, which is no longer online.

**Comment by jpmens** [comment]
We've had to shut it down. Please feel free to continue adding to 408
