### ISSUE TITLE
iBeacons Support with GPS disabled

### ISSUE THREAD

**Issue by GardenShedDevelopments** [owntracks/talk#31]
I have been using owntracks with GPS and iBeacon support for some time for me this works well however I have a use case where I need to be able to use iBeacons but without GPS being enabled.

I have tested this use case in many configurations within owntracks and it appears that position updates are not available  when entering or leaving a known iBeacon region with GPS disabled. When GPS is enabled this works fine.

is this a known configuration restriction ?

**Comment by ckrey** [comment]
I guess you are talking about Android

**Comment by GardenShedDevelopments** [comment]
apologies, I didnt state the device this is IOS/ iPhone

**Comment by ckrey** [comment]
You cannot switch off GPS on an iPhone. You switch off Location Services. iBeacon is implemented using Location Services.

**Comment by GardenShedDevelopments** [comment]
a true 'light bulb' moment !

My assumption has always been GPS = location services where as 'location services' really means GPS + wifi + cell data + iBeacons.

Thank you for clarifying
