### ISSUE TITLE
Scene radius - Beacon or Geofence?

### ISSUE THREAD

**Issue by chbardel** [owntracks/talk#33]
Is the radius from a scene for the geofence or the beacon? I am using Android was wondering if it is possible to use only beacon without geofence? It would be a huge downgrade if I cant track, when I am in my car. Or can I set the Geofence to a million kilometers or something and then it works?

**Comment by jpmens** [comment]
Closing for lack of reaction. Please re-create this ticket in Android tracker if necessary.
