### ISSUE TITLE
Hiding position of friends

### ISSUE THREAD

**Issue by jeppper** [owntracks/talk#35]
Hi
Is it possible to hide the position of friends in the OT iOS app? so only the position of the phones owner is visible?
I am using the position of family members for automations in Home Assistant but only when entering/leaving the home zone.

**Comment by jpmens** [comment]
Could you please clarify what the difference between a friend 's position an phone owner is?

**Comment by jeppper** [comment]
Sorry. On my iphone i just want to be able to show my own position in the OT app and not that of my girlfriend and kids and vice versa but still their entering/leaving the home zone has to trigger an event in Home Assistant.

**Comment by jpmens** [comment]
Set up ACLs on the broker to ensure your friends' positions don't reach your device but their events do. Our Booklft describes the MQTT topics we use.

**Comment by jeppper** [comment]
okay thanks. I will try to take a look into it.
