### ISSUE TITLE
Definitive Guide on Receiving Enter/Leave Messages 

### ISSUE THREAD

**Issue by NickSutton** [owntracks/talk#36]
Hi, completely new to MQTT and put what I’ve got so far together over a few days.
I have a private MQTT broker running on my main Rpi, which is then bridged to another Rpi that I use as a kind of wallboard display.

I’m running the iOS app to provide my location updates. 
I successfully get location lat/Lon battery info etc with the latest version of the app 9.8.4, on iOS 11.2.2

Regions were defined in the app, are shared, and all permissions seem to be as expected. The app connects fine (over TLS - which was a mission!) and I can see the ‘badge icon’ counter as well as notifications flash up on my watch when I enter / leave a defined region... But that’s as far as those enter/leave messages get, they don’t appear to arrive at my MQTT broker and certainly not getting to my bridged device.

I’ve just enabled output logging (of the MQTT broker to txt) to make sure the messages are getting on to my network, I want to rule out any subscription issues, as this has confused me a little (mostly, around the bridging). All the messages I receive currently are from ‘owntracks/my user ID/my device name’. I’ve tried a trailing ‘/‘ and ‘/#’ but then have problems starting the server.

I’m reluctant to raise an issue straight away, as I’m so new to this I’m confident I’ve overlooked something somewhere, and as I can see the notifications on the phone.. I don’t think the app is the problem.

Has anyone got any thoughts as to why the broker might not be receiving the region event updates? 

Thanks,
Nick

**Comment by jpmens** [comment]
Show us the ACL you've configured on your brokers for OwnTracks devices.

**Comment by NickSutton** [comment]
Thanks,

I’ve not yet configured ACL, as I’m the only user. Is it a requirement?

I currently have a .sh file run at boot with a mosquitto_sub line that has something along the lines of ‘OwnTracks/my user/my device’ as the topic, the rest of the string is user, pwd, and TLS details.

Is a subscription to  ‘OwnTracks/my user/my device’ the same as  ‘OwnTracks/my user/my device/#’

Also I got confused in the docs where I saw  ‘OwnTracks/my user/event’, does this mean I need to subscribe to more than one topic at boot? And if so, how to do this without launching multiple instances of mosquitto_sub?

Thanks for your help with this

**Comment by jpmens** [comment]
Have you taken the trouble of reading the man page of `mosquitto_sub`? It doesn't look like it...

The two topics you mention `owntracks/my-user/my-device` and `owntracks/my-user/my-device/#` don't look the same do they? They're not. The `#` is a wild card.

Try subscribing to `owntracks/#`, and I think you'll see it all. Or even `#` if you're alone.

**Comment by NickSutton** [comment]
I have subscribed to ‘owntracks/#’ just before a few days away, so I can test the regions.
