### ISSUE TITLE
iOS App development

### ISSUE THREAD

**Issue by NickSutton** [owntracks/talk#38]
Hi,
Had an idea for the app, 3D Touch on icon to quickly change modes?
I’ve found ‘move’ mode quite heavy on battery usage so was thinking of ways to make switching modes as easy as possible.

Hope this helps, keep up the good work!

**Comment by jpmens** [comment]
Nice idea. Could also add a "Publish now" perhaps.

Do us a favor: for future iOS issues/ideas please use our iOS issue tracker; thank you.
