### ISSUE TITLE
Regions not saved

### ISSUE THREAD

**Issue by vandan380** [owntracks/talk#39]
hi,

i'm a newby in using owntracks :D 

i don't know if it is a mistake by me or an issue. i try to save a region, but after exiting the app and start it again, the region is not longer available. 

i've tried it in public and in private mode.

i am using a iphone se 11.2.5 and owntracks 9.8.4/de_DE.

**Comment by jpmens** [comment]
This issue is off-topic here. Please open it at our [iOS tracker](https://github.com/owntracks/ios/issues).
