### ISSUE TITLE
Android, IBeacons and Owntracks

### ISSUE THREAD

**Issue by rdehuyss** [owntracks/talk#4]
Hi, great idea to use the issues for communication!

Small question: regarding iBeacon support in Android...
- I setup an iBeacon on my raspberry pi 3 as follows (https://andrewmemory.wordpress.com/2016/03/29/turning-a-raspberry-pi-3-into-an-ibeacon/)
using UUID e7a3a5a9-1ed4-4ae7-bfaa-2898514cedff, major 0201, minor 0001
- using iBKS config tool on my android phone I can see the raspberry pi transmitting iBeacon packets
- I configured owntracks on Android with a region as follows:
  - Description: '-home'
  - Latitude: 0
  - Longitude: 0
  - Radius: 0
  - Beacon uuid: e7a3a5a9-1ed4-4ae7-bfaa-2898514cedff (I also tried without the dashes as noted in iBKS)
  - Beacon major: 201
  - Beacon minor: 1
  - Share: true

Yet my mqtt messages don't contain anything regarding me entering or leaving the region.
Any idea what I'm doing wrong?

![screenshot_20170113-221611](https://cloud.githubusercontent.com/assets/567842/21945890/2a41644e-d9de-11e6-9b2b-11e7ff63971a.png)

![screenshot_20170113-221626](https://cloud.githubusercontent.com/assets/567842/21945894/2eae2094-d9de-11e6-910a-b29250dfe22e.png)

**Comment by rdehuyss** [comment]
Solved it by cloning the Android repo and bumping the version of AltBeacon to 2.9.2.

In my fork, I also show the region in red as in the IPhone version... interested in a pull request?

Cheers,
R

**Comment by binarybucks** [comment]
Yes please!

**Comment by rdehuyss** [comment]
Done, see pull request #443
