### ISSUE TITLE
cards: Can we increase the user image resolution?

### ISSUE THREAD

**Issue by ardevd** [owntracks/talk#41]
Currently the helper scripts for generating the json data for the info cards use ImageMagick to scale the images down to 40x40 pixels. The end result is a visibly blurry image, at least in the Android app. I've tried modifying the scripts to increase the image size but the resulting json files are seemingly just disregarded server-side.

**Comment by jpmens** [comment]
My understanding is the client apps show 40x40 irrespective of what you have server-side, i.e in the CARD. 

You say the "resulting JSON files are disregarded server-side"; what do you mean by that?

**Comment by ardevd** [comment]
By that I mean that if I subscribe with `mosquitto_sub` I can see the face data I post. If I post card data with the 40x40 image it shows up like you would expect it to. However, if I post card data with a larger image, it doesnt show up in my subscriber. I dont know much about MQTT but I figured perhaps the payload data size is too large? Idk. 

I played around with the card generation scripts a lot yesterday and I experienced three different behaviors:

- I could see the post with mosquitto_sub and the card data showed up in the owntracks app
- I could see the post with the mosquitto_sub but the old card data showed up in the owntracks app.
- I could not see the post with mosquitto_sub and the old card data showed up in the owntracks app.

To replicate this, simply try running this [image2card.sh](https://gist.github.com/ardevd/f17d60faba60d3afc03f1075dad02380) script on a larger jpg after you modify line 44

**Comment by jpmens** [comment]
Make sure you're not being bitten by a bug in an older mosquitto_pub version in which string payload over (1024 iirc) bytes is being truncated; in other words, that would publish but the apps wouldn't use it because the payload is a corrupt base64-encoded image blob. 

To test, print the base64 as it's being published and *verify* that actually is what you've then got retained broker-side.

**Comment by ardevd** [comment]
But if that was the issue I'm assuming no image would show up at all? In my case I still see the old card image and name.

**Comment by jpmens** [comment]
Show me how to reproduce your issue.

**Comment by ardevd** [comment]
@jpmens did you try my instructions in the post abive?

**Comment by jpmens** [comment]
You need to prove the breakage to me; I still think your base64 is getting truncated. Prove to me it isn't

**Comment by ardevd** [comment]
I'm using the latest version of the docker image. 

`mosquitto_sub version 1.4.14 running on libmosquitto 1.4.14.`

**Comment by jpmens** [comment]
```
$ file iss17.png
iss17.png: PNG image data, 225 x 225, 8-bit colormap, non-interlaced

$ sh image2card.sh iss17.png ISS > iss.b64
$ mosquitto_pub -h localhost -p 1888 -t owntracks/ardevd/device/info -f iss.b64 -r

$ mosquitto_sub -p 1888  -t 'owntracks/ardevd/#' -C 1 > sub.json
$ jq -r '.face' < sub.json > img.data.b64
$ base64 -D -o newface.jpg -i img.data.b64
$ file newface.jpg
newface.jpg: PNG image data, 80 x 80, 8-bit/color RGB, non-interlaced
```

**Comment by jpmens** [comment]
I will assume this works for you as well.
