### ISSUE TITLE
Cards in http payload

### ISSUE THREAD

**Issue by mbirth** [owntracks/talk#44]
The booklet says we can also [return cards](http://owntracks.org/booklet/tech/http/) in a HTTP response, yet the [JSON structure](http://owntracks.org/booklet/tech/json/) only lists `name` and `face` for a card. How do I map a card to a tid or user in HTTP mode?

**Comment by jpmens** [comment]
You are correct: the documentation is incomplete. I've just checked the Recorder's source, in which I write:

> Each of the objects in this array *must* contain a TID as the apps will use that to construct a ficticious topic name (owntracks/_http/<tid>) internally.

So, to answer your question, you need the `tid` element in the JSON.

I'd appreciate you testing that for veracity (and if possible providing either a small pull request for the booklet, or a short note here for us to update the documentation)

**Comment by mbirth** [comment]
Got around to test it and it works. Names and faces are shown properly.

Am I correct that with the Android app it's currently not possible to map tids to an address book contact? Since each face adds ~15+ kB to the payload, that would be preferable.
