### ISSUE TITLE
Forcing a location update via MQTT

### ISSUE THREAD

**Issue by bkmar1192** [owntracks/talk#46]
Is it possible to publish a message to the MQTT broker to force a location update?  According to the guide, it looks like it is but I can't get owntracks to respond.  I have tried numerous combinations but thinking it would be:

topic: owntracks/user/id/cmd/action
message: reportLocation

**Comment by ckrey** [comment]
@bkmar1192 the message is JSON as described here: http://owntracks.org/booklet/tech/json/

`{"_type":"cmd","action":"reportLocation"}`

Don't forget to use QoS1 or QoS2 because the device might be in background (iOS) at the moment. It will pick up the command when it wakes up the next time.

**Comment by dgolda** [comment]
So maybe it should be possible to send such request from Android app? For example by "Request location" button?

**Comment by binarybucks** [comment]
This feature has been removed because it could not be guaranteed that the device will respond to the command right away for reasons noted by @ckrey. Also, the topic is `owntracks/user/id/cmd` and not `owntracks/user/id/cmd/action`.

**Comment by bkmar1192** [comment]
How often does the iOS app wake up?

**Comment by jpmens** [comment]
That is determined and decided by the OS, and we have no influence on that.
