### ISSUE TITLE
ANSWERED - Concentric Region Transition Events

### ISSUE THREAD

**Issue by meingraham** [owntracks/talk#48]
I have three concentric regions defined: R1 within R2 which in turn is within R3.

- Are the regions concentric "bands" or overlapping circles? If I 'leave' R1 do I 'enter' R2 and R3 or just R2?
- How does OwnTracks differentiate a transition when leaving R3 and entering R2 vs. leaving R3 as I go further away?

Also, I just wanted to confirm that ON equates to an 'enter' transition and OFF equates to 'leave'.

Regards.

Mike

**Comment by meingraham** [comment]
Has anyone set up anything similar and know how regions should behave? For me they are behaving as concentric, overlapping regions rather than "isolated" rings.

**Comment by jpmens** [comment]
I’ve not a clue and have never tested that.

**Comment by ckrey** [comment]
All regions are treated independently as if they were not overlapping

**Comment by meingraham** [comment]
@ckrey That confirms what I'm seeing. Thanks.
