### ISSUE TITLE
Sharing a region 

### ISSUE THREAD

**Issue by mabnz** [owntracks/talk#49]
As of 9.9.3 it appears functionality to share regions has been removed.

What is the recommended way to share regions now to use with OH2?

Cheers
Mike

**Comment by jpmens** [comment]
Regions are now shared by default; we removed the switch because most people do not not share.

**Comment by jpmens** [comment]
@mabnz do us a favor please and report iOS-only issues in our iOS tracker at `../ios`. Thank you.

**Comment by jpmens** [comment]
(Although I should clarify that the behavior will be the same on Android: no switch)

**Comment by mabnz** [comment]
Will do - thanks for clarifying JP.
