### ISSUE TITLE
bridging no working from app

### ISSUE THREAD

**Issue by gaudihub** [owntracks/talk#5]
Hi there,

while I'm sure my problem is not a software issue, but rather user errors, it still drives my crazy and I haven't found another place to post this cry for help...

I have setup mosquitto with TLS on a local RPi2 to manage owntracks as well as a couple of smarthome appliances. The broker is configured as a bridge (topic # both 1) to interface with AWS IoT. Almost all tests have passed with positive results:

- a topic published on my local RPI can be subscribed locally as well as via AWS IoT
- an AWS IoT published topic can be subscribed locally
- topics published on other clients on another RPi (in the local network) are seen by the broker-RPi as well as AWS Iot

With that, my conclusion is that the mosquitto and bridge setup to AWS Iot seems to be working o.k.

Now on to owntracks... 

- a local subscriber can see all client topics from a number of cell phones. 
- the phones can subscribe to other clients (phones)
- a mosquitto_sub client on another local RPi can subscribe to the owntrack topics

All good - except, that for some weird reason, the owntrack topics are not forwarded to the AWS IoT client?!?!

Any idea/suggestion/recommendation where to look to fix this?

**Comment by jpmens** [comment]
OwnTracks apps publish with QoS=2; that may (or may not) be a reason: I have no experience with AWS IoT but seem to recall something regarding QoS; check their documentation.

**Comment by gaudihub** [comment]
thanks for your swift reply! And you are right, AWS does not support publishing or subscribing with QOS 2. That said, my understanding was that this only indicates the behavior of the client. I just tried it, and AWS does show a topic that is published from another client with QOS 2, so something else must play a role, I guess?! Still puzzling...

**Comment by gaudihub** [comment]
o.k., worked on it throughout the weekend - with no success. 
I don't think the QoS=2 lead is the reason as I can publish topics from various clients with QoS=2 and they get pushed through to AWS IoT. I've played around with certificates and authorizations, but again, no improvement. It's weird as everything else in my setup seems to work except for this bit. 

I will have to give it a break now, hoping one day someone get's to a similar setup with success and is willing to share.

**Comment by ckrey** [comment]
AWS IoT does not support retained messages either. 

While the QoS of a messages is valid only point to point (e.g. phone to local broker) and is overridden by the bridge qos settings, the retained attribute is end to end.

To overcome the AWS IoT problem, you will have to republish the original message without retained flag. 

To reiterate: AWS IoT dies not implement the MQTT 3.1.1 spec  (http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html).

Outlook: The MQTT 5 spec will make the AWS IoT implementation compliant but a number of MQTT features will become optional.

**Comment by gaudihub** [comment]
Christoph, thanks for your expert advice! 
I've tried with the pubRetain flag in the owntracks config set to false, but it didn't do anything. I might have looked at the wrong flag/place though?! Your point about republishing the message is probably the easiest way to work around this. I'm not aware of a feature in the mqtt broker to accomplish that, but I think it should be relatively straight forward (albeit not most elegant) through a little python script to accomplish that for now...

**Comment by jpmens** [comment]
A broker can typicall not do this, but as you say, as simple Python program certainly could. Alternatively, you could try using [mqttwarn](https://github.com/jpmens/mqttwarn) if you're already using it for something else.

**Comment by gaudihub** [comment]
o.k., folks, here's a quick update on this. Technically, I have not been able to solve this issue, but I was able to create a workaround based on the above recommendations. For now, I have simply put a small and simple Python program in place that subscribes to the topics of interest and then re-publishes them back to the broker. I'm still not sure what the issue is, but I'm able to see the topics on AWS IoT now, so the fix works for me at this point. I will for sure go ahead and try mqttwarn as that looks very promising for this as well as a number of other tasks I have in mind.

So, while not fully resolved, I will close this issue for now. Maybe one day we can re-open it and post a fix to the original challenge.
