### ISSUE TITLE
Documenting HTTP mode JSON responses

### ISSUE THREAD

**Issue by kaspergrubbe** [owntracks/talk#50]
Hi!

Thanks for an awesome product. I have currently tracked over 9000+ movements of my two iOS devices since 2017-07-16 with your tool.

Currently I am using the HTTP-mode with the JSON endpoint, and that works great, I just listen for `params["_type"] == "location"`, and process the request.

I am currently looking to implement the steps counter, which seems to not be enabled by default, but is requiring me to implement `cmd`-object in order for me to tell the device to send me steps, is that correct?

![2dwehg](https://cdn.servnice.com/screenie/TUR6NKnvOZzuyxW.jpg)

Will that just force the iOS device to send me steps once, or will it send me steps periodically?

Would it be possible to include a full and proper JSON response with two commands (for an example `reportSteps` and `reportLocation`) in the same command?

**Comment by ckrey** [comment]
1) it will send you the steps once. 
2) It already does, just include two `cmd`s in the JSON array returned

**Comment by kaspergrubbe** [comment]
@ckrey Could you give me an example of the two `cmd` that I need to return?

**Comment by ckrey** [comment]
> [{"_type":"cmd","action":"reportLocation"},{"_type":"cmd","action":"reportSteps"}]

**Comment by kaspergrubbe** [comment]
Maybe my problem is that I can't wrap my head around the documentation.

> [{"_type":"cmd","action":"reportLocation"},{"_type":"cmd","action":"reportSteps"}]

That is valid JSON, however the one in the booklet isn't valid:

```json
{"_type":"cmd","action":"reportLocation"}
{"_type":"cmd","action":"reportSteps"}
{"_type":"cmd","action":"dump"}
{"_type":"cmd","action":"waypoints"}
{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration",...}
{"_type":"cmd","action":"setWaypoints","waypoints":{"_type":"waypoints","waypoints":[...]}
{"_type":"cmd","action":"action","content":"Backend maintenance scheduled for tonight\n\nhttp://support.owntracks.org"}
{"_type":"cmd","action":"action","content":"<a href='http://support.owntracks.org'>Backend Maintenance tonight</a>"}
{"_type":"cmd","action":"action","url":"http://support.owntracks.org"}
```

Maybe the documentation just need a full implementation example.
