### ISSUE TITLE
Avatars and notifications

### ISSUE THREAD

**Issue by ptersilie** [owntracks/talk#52]
I've tried to give my contacts in the app a name and an avatar but couldn't find the option to connect a friend to a phone contact as described in the documentation. Am I correct assuming that this feature doesn't exist anymore and has been replaced with CARDs? The documentation seems to suggest, that CARDs only work in HTTP mode? Is that also correct?

Also, is there a way to hide notifications like "user left zone/user entered zone" if that user is myself, as in that case this information isn't very useful?

**Comment by ptersilie** [comment]
I think it was the following sentence which confused me: "We developed a new feature we call a card which you can use when in Private mode and in HTTP mode." Maybe it should be "Private mode _or_ in HTTP mode"?

I guess to see if the system is working this is useful, but once I know it does work I don't really need to notify myself leaving or entering a zone. ;-) Maybe an option in the settings to turn it off could be useful?

I'm on Android. I assume the code responsible for that notification would be here: https://github.com/owntracks/android/blob/84f217041183ffb7434f1cb0c4f304ac3e70c333/project/app/src/main/java/org/owntracks/android/services/BackgroundService.java#L308

**Comment by ptersilie** [comment]
Would you be interested in a PR for this?

**Comment by binarybucks** [comment]
That feature request never occurred but I’d accept a PR for it. Should be rather easy by adding a new config key (e.g. notificationEventsIgnoreSelf) and checking that before sending a notification.

**Comment by jpmens** [comment]
Notify except self sounds like a clever idea.

**Comment by ptersilie** [comment]
Cool, so here's what I got so far: https://github.com/owntracks/android/pull/584

I'm not sure if the location where I do the check is the right one and if comparing the tracker IDs is enough to check if the event is related to the main user.

I also noticed some inconsistencies in `CONTROBUTIONS.md` which I fixed. I'm happy to move them to a separate PR if they shouldn't be in the that one. One thing I haven't added yet, which I think should be in there tho, is that the Google Maps API is not enough as one also has to enable Geolocations API. At least I think so. Would be great if someone can confirm this, then I can edit the contributions file again.

**Comment by morrydavis** [comment]
Why do I keep getting notifications about leaving or entering a point 2 days later?

**Comment by morrydavis** [comment]
What is the significance of the badge mine is up to 1,602

**Comment by jpmens** [comment]
@morrydavis it sounds to me as though you're using our iOS app, is that right? If so, is your broker actually accepting messages from the app because the counter on the badge indicates it isn't.

**Comment by morrydavis** [comment]
Yes it is ios we have 2 phones mine and my wifes hers does not get the
badge. We us mqtt.flespi.io and we both use the same userid. The other
thing  is when I look at my phone I don't see her location  updating on my
phone. I met her some where yesterday  and she was right next to me and on
my phone it showed her 30 miles away.

**Comment by jpmens** [comment]
Configure the phones with different userIDs and clientIds.

**Comment by morrydavis** [comment]
I see UserID but I don't see anything that says clientid this is where I
run into lots of problems, Alot of instructions I find seem to be geared
around Android and few around ios
