### ISSUE TITLE
Tracking aircraft with Owntracks

### ISSUE THREAD

**Issue by vielmetti** [owntracks/talk#54]
I'm using 

https://github.com/jpmens/1090-to-owntracks

to feed ADS-B data from a `dump1090` based system for tracking airplane locations into Owntracks. It's pretty nifty, I've collected 2000+ aircraft and flight tracks in only two days from my location near enough to Detroit Metro Airport to get a bunch of their traffic.

If anyone else is using this code (or is interested in it) I'd love to compare notes. 

Thanks @jpmens for the original code from two years back, just got time to dust it off in a new configuration that works pretty well.

**Comment by jpmens** [comment]
Thanks for your report, @vielmetti, and for your kind words. I'm glad it's of use to you, and please don't hesitate to suggest or better yet provide improvements.

**Comment by vielmetti** [comment]
By taking owntracks data, munging it up some, following the instructions from several tutorials, and generally bumbling around, I was able to generate this graph of the airspace that I can see around my house:

<img width="1033" alt="screen shot 2018-11-24 at 1 42 10 am" src="https://user-images.githubusercontent.com/35047/48965525-1ebe1100-ef8d-11e8-91b9-068596c70f6f.png">

The visualization was done with plot3D and plotrgl which are packages in R. I found this tutorial to be helpful for visualization and would be intrigued to think that it might be helpful for other visualizations of other Owntracks data sets. 

http://www.sthda.com/english/wiki/impressive-package-for-3d-and-4d-graph-r-software-and-data-visualization

**Comment by vielmetti** [comment]
I wrote up what I learned here (so I won't forget it) as "Visualizing airplane tracks with dump1090, Owntracks, R and scatter3D()"

https://vielmetti.typepad.com/w8emv/2018/11/visualizing-airplane-tracks-with-dump1090-owntracks-r-and-scatter3d.html

**Comment by jpmens** [comment]
Thank you, @vielmetti. If I could please ask you for a favor: in the first paragraph you write

> It's written by JP Mens

and I get the impression you mean the works of OwnTracks are by me, but that's inaccurate. While I created the idea, the mobile apps were written by Christoph Krey and Alexander Rust; I just cobbled bits of the backend together.

**Comment by vielmetti** [comment]
Fixed! First paragraph now reads

>  JP Mens created the idea and developed
the back end server; the mobile apps for Owntracks are by Christoph Krey and Alexander Rust.
