### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by AuspeXeu** [owntracks/talk#55]
How about supporting to add multiple accounts? For example, if you have an MQTT server for your family but also a separate one hosted by one of your friends.

**Comment by binarybucks** [comment]
Couldn’t that easily be solved with sever side bridging?

**Comment by AuspeXeu** [comment]
Thanks for the quick clarification. In general however, this does not give the users control over permissions but rather makes the server admin responsible for all this, right?

**Comment by jpmens** [comment]
That is correct, yes, and typically the way you'd want it. For example, if you share my broker with me I would possibly allow you to see where I am in OwnTracks, but would forbid you seeing where my family members are.

**Comment by jpmens** [comment]
Quite right.

Now consider what would happen if we provided the possibility of adding multiple accounts. The next step would be that you'd want to be able to control which location publish goes to which account(s), which event goes to which account(s), etc. That would be very confusing, I think.

**Comment by gdt** [comment]
I think it makes sense to have the app user be able to control publishing to multiple places.   I see your point about broker admin, but that's really an intermediate role between user and corporate cloud provider.

An example use case is always wanting to share location with family, and being able to turn on sharing with a friends group sometimes.  I don't see how this can be done server side, by the user who isn't an admin on the server.

It is probably useful to look at phonetrack-android, which supports the notion of multiple logging jobs, where each has a server and session, as well as time/distance, and can be individually enabled.   Leaving the "family" logjob enabled and turning on and off the "club" logjob does not seem confusing (although certainly it's a few more activities to code up).

**Comment by ckrey** [comment]
Currently we do not support any time/distance limited sharing schemes (WhatsApp and others do provide such functionality) nor do we have multiple "logging jobs" based on servers or user groups.

There are no plans to implement any of those features.

**Comment by AuspeXeu** [comment]
Why?

**Comment by jpmens** [comment]
why what? why we're not going to implement this? For a number of reasons including not desiring to, not considering it necessary, and not having either time or inclination. We are a small open source project. If you want this feature, we can quote you our daily rate or you provide the code for both Android and iOS.

**Comment by AuspeXeu** [comment]
Thanks for providing some background on this :)

**Comment by Byter3** [comment]
Hey!
I read the comments, I realize that this is a big ask, but just FYI +1 for multiple accounts, or multiple target server/sessions for logging. I use this feature all the time on a sperate app, one session for friends, one session for family, and one session for my spouse, but I would like to see a similar option in owntracks as well. Again just an FYI, maybe if enugh people indicate that this would be something they want to use, you would considering implementing it. Thanks anyway!

**Comment by alexkutsan** [comment]
This would be a great feature for otrecorder to support multiple users at least in HTTP mode. 
mqtt traks structure is already fit multiuser traks feature : 
otrecorder creates named topic for `OTR_USER`
![image](https://user-images.githubusercontent.com/860357/171378982-292f173d-fb81-4edc-932c-33729fb83718.png)

owntracks-frontend also have UI prerequisites to split users : 
![image](https://user-images.githubusercontent.com/860357/171379781-2d19b5fe-94e8-48d0-88a0-a4e3d443e6e8.png)


The problem is that MQTT access authentication is the same as the topic created by otrecorder. 
otrecorder would split MQTT auth and, HTTP auth it would be able to create multiple tracks.

So if you have MQTT access you can read\write all user's tracks.
But there is a way to create user\password for HTTP publisher without providing access to tracks reading. 

the concept is like this: 
```
#  /config/recorder.conf
MQTT_USER = alice
MQTT_PASSWORD = *****************
HTTP_PUBLISHEDRS  /config/http_users.json 
```

```
#  /config/http_users.json
{
  "alex" : hashed_password
  "alice : hashed_password
  "olgs : hashed_password
}
```
