### ISSUE TITLE
Ability to detect places you are visiting

### ISSUE THREAD

**Issue by aindilis** [owntracks/talk#58]
Hi,

This is probably a noob question.  I am wondering - I'd like to have some server side code that detected, like Google does, when the user visits a particular place.  For instance, if I went to a particular supermarket, the code would recognize this and log an event or call a handler.  That way, I could lodge a reminder to scan the receipt (for example).  I was wondering if there was such code, or if I should write it.   I am fine with it calling Google Places API, or OpenRouteService Geocode API (in fact I have both these wrapped for Perl).  I call this "Location Logic" in this paper: https://frdcsa.org/visual-aid/pdf/Temporal-Planning-and-Inferencing-for-Personal-Task-Management-with-SPSE2.pdf  I am also interested in integrating RTEC https://github.com/aartikis/RTEC  Secondly, I am interested in knowing if there are default approaches to sensor integration/fusion that are specifically designed to work with OwnTracks.  For instance, integrating with zmeventmanager https://github.com/pliablepixels/zmeventserver  Thank you so much for having written OwnTracks, it is amazing!

Andy

**Comment by jpmens** [comment]
Our apps already "detect" places you visit. You can set up what we call _waypoints_ or geo fences in the app, and they will alert via a JSON event which is published to MQTT (or posted to HTTP) when you enter and/or leave the region. From there you can trigger something to happen using, for instance, [mqttwarn](https://github.com/jpmens/mqttwarn) or similar system.

**Comment by aindilis** [comment]
Thank you for replying so quickly!  I was wondering, must the waypoints be specified in advance?  For instance, if it sees that you are hovering around a location you don't have a waypoint for and have never been to before, can it call the geocoding to get the place data, such as name, address, phone number etc?  So for instance, if I went to a Starbucks in a different city, it would log that I had been to that Starbucks?  Thanks again.  If not, should this be something that I write and if so what is the preferred tech stack?  Thanks!

**Comment by jpmens** [comment]
Waypoints are specified in advance because it's the operating system of the mobile device which watches over them.

If you want to be able to detect any location you will probably, as you've already guessed, have to do this server-side by subscribing to MQTT, obtaining location publishes as they appear, and then reacting to a particular lat/lon point.

This is not particularly hard to do, but the devil is in the details. For example, your coffee shop might actually reverse-geocode to something without its name in it, so you wont catch `"Coffe Shop Brand"` easily.

**Comment by aindilis** [comment]
Okay I will do this in Perl (since that's my stack) and post to GitHub, and follow up with a link here.  Thanks for taking the time to answer my questions, the info (mqttwarn) and the heads up about the pitfalls of reverse-geocoding!
