### ISSUE TITLE
Report Wifi changes

### ISSUE THREAD

**Issue by MeneDev** [owntracks/talk#59]
I think for many use-cases reporting uppon (dis)connecting from a wifi is helpful.

Examples:
* Enter/Leave work wifi to track work times
* Enter/Leave home wifi for smart home presence detection
* Enter/Leave friends wifi for diary

Feasibility:

Android
https://stackoverflow.com/questions/5888502/how-to-detect-when-wifi-connection-has-been-established-in-android

iOS
Notification: https://stackoverflow.com/questions/27310465/detecting-network-connectivity-changes-using-reachability-nsnotification-and-ne
Getting SSID: https://stackoverflow.com/questions/50767946/systemconfiguration-captivenetwork-doesnt-work-on-ios-12

**Comment by jpmens** [comment]
We discussed doing this a year or so ago, and decided not to add to the featureset, in particular (IIRC) because those methods weren't very reliable.

**Comment by binarybucks** [comment]
Regarding Android: See https://github.com/owntracks/android/issues/642 or the countless other issues for that. 
We might eventually add that if anyone can dedicate some time.

**Comment by MeneDev** [comment]
Pitty. Sorry if I reposted anything, was only looking in the talk project rather than android/ios.
