### ISSUE TITLE
Forward mqttitude.org to owntracks.org

### ISSUE THREAD

**Issue by almereyda** [owntracks/talk#6]
The http://owntracks.org/booklet/images/OwnTracksPosterA4.png shows a tweet mentioning mqttitude.org, which, given the architecture, is probably owntracks. Since the domain still exists and points at GitHub pages, it could be nice to install a simple page with a client-side redirection under that `CNAME`, what do you think?

**Comment by jpmens** [comment]
Nice idea, but we'll probably not keep the name alive much longer.
