### ISSUE TITLE
Booklet outdated for functioning of Android app?

### ISSUE THREAD

**Issue by Thorarin** [owntracks/talk#61]
The information in the OwnTracks Booklet appears outdated regarding the way the Android app obtains location data? (https://owntracks.org/booklet/features/location/#android). Or perhaps it's just not telling the whole story?

What's described there is purely a polling mechanism. From what I glanced in the code of the app, it does appear to make use of the Android Geofencing API for monitoring regions, or am I mistaken? Additionally the text doesn't mention the different monitoring modes which (at least in name) are actually quite similar to the ones described for iOS.

I realize it could be a significant rewrite to update the page, but I thought it was a very interesting read. It also left me a bit disappointed that I switched to Android last year, but as I mentioned I think the difference in sophistication isn't quite as dramatic?

Anyway, keep up the good work 🙂

**Comment by jpmens** [comment]
Thank you for point that out, and we'd love to see a pull request from you updating the documentation. :-)

**Comment by Thorarin** [comment]
One slight problem is that I would have to reverse engineer things to write accurate and detailed documentation 🙂

**Comment by meingraham** [comment]
@jpmens,

A few months ago the Android app added location publication modes which appear to replicate the functionality of the iOS app. If the functionality is equivalent, I'm happy to make the updates via the "Edit on GitHub" mechanism. Not knowing anything specific, what I'm proposing is to copy the section on the four modes that is currently in the iOS section and replicate that text in the Android app section. Would this accurately represent the new Android feature?

Mike

**Comment by jpmens** [comment]
@meingraham that would be much appreciated, thank you; please do, and we'll tweak if required.

**Comment by meingraham** [comment]
OK... I think I created the PR.

https://github.com/owntracks/booklet/pull/42

**Comment by jpmens** [comment]
Merged, thank you.
