### ISSUE TITLE
tracking multiple trucks

### ISSUE THREAD

**Issue by frank3427** [owntracks/talk#63]
we have several trucks , semi, bobtail and van are the type of trucks we use
I was thinking of setting up our Owntracks. how can I setup/build a client that is preconfigured to our server and the only thing that needs to be setup in the truck number and select type.
we could then use type to filter groups of trucks on the map.
I also would like to cert auth the client.
I guess one could use type = account

**Comment by jpmens** [comment]
You could use the source code, configure that appropriately and provide that. On the other hand you could use our OTRC configuration files and have those sent to the devices. 

Be aware that if you are trying to track those vehicles professionally, the apps will probably not satisfy your needs.
