### ISSUE TITLE
Owntrack Integration with Thingsboard

### ISSUE THREAD

**Issue by cjkini** [owntracks/talk#64]
Guys,
I tried to integrate the Onwtrack apss to Thingsboard platform via Thingsboard MQTT server. Everything worked well, I manage to get the GPS data plotted in Thingsboard. However ,when I connect the second owntrack apps, what happened is, the second owntrack apps will be sending the data, while the first app will be stuck status initializing and cannot send data to thingsboard.
May I know, what I need to do to solve this problem?
Thanks

**Comment by jpmens** [comment]
Have you configured both apps with the same clientId? If so, then one might be kicking the other out. MQTT client Ids must be unique server-side.

**Comment by jpmens** [comment]
Closing due to lack of response.
