### ISSUE TITLE
Add TLS certificate to repo.owntracks.org

### ISSUE THREAD

**Issue by makubi** [owntracks/talk#68]
Hi,

the current README for the installation of ot-recorder (https://github.com/owntracks/recorder) using packages suggests to add the PGP key at http://repo.owntracks.org/repo.owntracks.org.gpg.key, but this endpoint is not secured using TLS. Please add a certificate, redirect HTTP requests and update the README.

Thanks

**Comment by makubi** [comment]
Just found the issue at https://github.com/owntracks/recorder/issues/113. Feel free to close this and maybe just update the README so that it uses the Github URL.

**Comment by jpmens** [comment]
We'll accept a PR
