### ISSUE TITLE
Documentation for HTTP responses?

### ISSUE THREAD

**Issue by e7o-de** [owntracks/talk#7]
Hey Guys,

Stumpled over your nice project and wanted to have a look into it ... looks promising. Started with your example PHP script for recording via HTTP and found this sentence in your documentation (digging into this right now):

> Support for Friends is available if your HTTP endpoint can produce appropriate data

What does that mean? I mean, it's obvious that I can return an array of some fancy JSON objects, like location objects for the other users containing cards--at least that's what I'll try the next days (if nobody says it isn't worth trying), but it would be great if this would be somehow reflected in the documentation ;)

**Comment by jpmens** [comment]
Are [this page](http://owntracks.org/booklet/tech/http/) and [this page](http://owntracks.org/booklet/tech/json/) not sufficient in terms of documentation? We'll gladly accept an appropriate pull-request to the booklet.

**Comment by e7o-de** [comment]
Thx for your reply. Sure, they're enough, but for some reason I find it missleading. Still thinking how the text could be improved there. Maybe it's because it's no copy-paste-solution and I'm too lazy to think about it? Not sure :)

Sorry for bothering you, looks like it's already the best sentence you could put there and I just missed it ... I guess you can delete this thread, can't contribute anything right now :)
