### ISSUE TITLE
set monitoring mode remotely (http) mode

### ISSUE THREAD

**Issue by pergolafabio** [owntracks/talk#70]
Hi , i am new to this app
but is it possible to set the monitoring mode remotely in http mode?

can someone provide me an example how to do this?

thnx in advance

**Comment by hyteoo** [comment]
Yes

If you look at the docs (https://owntracks.org/booklet/tech/json/#_typeconfiguration)
You can send this with the HTTP response for example Move monitoring (2)

{
    "_type":"cmd",
    "action":"setConfiguration",
    "configuration":
    {
        "_type": "configuration",
        "monitoring": 2
    }
}

**Comment by pergolafabio** [comment]
Thx, but I am not sure how to setup this with home assistant for example

**Comment by jpmens** [comment]
You will have to ask people familiar with HomeAssitant, please.
