### ISSUE TITLE
[Feature request] Battery charge status

### ISSUE THREAD

**Issue by hyteoo** [owntracks/talk#71]
As the battery is a very sensitive topic for an app like this, reporting the charge status would be a requirement.
The app itself doesn't have the logic to adapt - for ex. change monitoring mode depending on the charging status and battery %. And I agree, this doesn't necessarily need to be on the app. That logic can be moved on the server side. But in order to do that, we also need the charge status

A basic report would be

- not charging
- charging

An extended reporting could be

- not charging
- charging (wired)
- charging (wired, fast)
- charging (wireless)
- charging (wireless, fast)

**Comment by ckrey** [comment]
Battery status available in iOS:

![Bildschirmfoto 2019-08-27 um 09 53 42](https://user-images.githubusercontent.com/4027289/63752126-f9aa5600-c8b0-11e9-8d6d-6193f6f281f7.png)

**Comment by jpmens** [comment]
@hyteoo if the app reported the status (charging, not charging, full) you would then, server-side, change the monitoring mode on our app?

I fail to see how this is useful with one exception: move mode while plugged into a car battery.

Can you elaborate please?

**Comment by hyteoo** [comment]
> Battery status available in iOS:
> 
> ![Bildschirmfoto 2019-08-27 um 09 53 42](https://user-images.githubusercontent.com/4027289/63752126-f9aa5600-c8b0-11e9-8d6d-6193f6f281f7.png)

That looks great. Any reason that's not implemented in Android?

**Comment by hyteoo** [comment]
> @hyteoo if the app reported the status (charging, not charging, full) you would then, server-side, change the monitoring mode on our app?
> 
> I fail to see how this is useful with one exception: move mode while plugged into a car battery.
> 
> Can you elaborate please?

Tablet installed in the car, plugged in while ignition is on - That is actually exactly one of my usecases.

Apart from that, i see this app as a little more than just a GPS tracking app. For example, if the phone is plugged in, charging but the battery percentage doesn't change, means there's a problem (battery issue/high drainage). And this is easier to monitor when the phone belongs to your kids

I am not sure if the benefits outweigh the implementation complexity here, but nevertheless it would be a useful addition, especially that it looks like it is already implemented in iOS.

**Comment by jpmens** [comment]
I don't think we have this in iOS yet; @ckrey was just showing what iOS provides in the API.

**Comment by ckrey** [comment]
See also #32

**Comment by hyteoo** [comment]
I saw that thread, however reporting on battery charge change would be too much in this case.
A simple addition of the battery charging state to the already existing report would suffice in my opinion. That will happen when the app is not sleeping and shouldn't cause a problem with the restrictions in ios.

However you know best if the effort outweighs the benefits in this case.

**Comment by jpmens** [comment]
This has been implemented in iOS; we cannot say whether or not it will be done for Android.
