### ISSUE TITLE
Transfer linusg/owntracks-ui to the owntracks organisation

### ISSUE THREAD

**Issue by linusg** [owntracks/talk#72]
Hi all,

A while ago I created a new frontend for OwnTracks, I initially [planned](https://github.com/owntracks/recorder/pull/287) to do this as a PR in https://github.com/owntracks/recorder, however abandoned this idea after realising integration into the recorder repo and packages might not be that easy.

I still think the project is a good addition to what OwnTracks delivers out of the box, so I want to know how how you feel about transferring [`linusg/owntracks-ui`](https://github.com/linusg/owntracks-ui) to e.g. [`owntracks/ui`](https://github.com/owntracks/owntracks-ui) or [`owntracks/frontend`](https://github.com/owntracks/frontend)?

I'll keep this short for now, there's no point in asking a bunch of additional questions or making assumptions before hearing a `hmm, maybe` or `nope, get out` 😉

Please let me know what you think, either way I'm looking forward to move to making "OwnTracks UI" more of a team effort instead of the current, slow-moving one-man operation. I'm trying to get v2 out [for months now](https://github.com/linusg/owntracks-ui/issues/4#issuecomment-482809136), which is a shame, but then again, there are only so many hours in a day.

**Comment by jpmens** [comment]
Hello Linus,

we haven't forgotten you :-)

We're glad you feel it's a good addition to OwnTracks, and to cut a long story short:  hand it over, and we'll gladly add your project to the OwnTracks 'portfolio'. :-) 

I think `owntracks/frontend` is probably a good choice for the name.

**Comment by linusg** [comment]
That's great!

![image](https://user-images.githubusercontent.com/19366641/64183517-e9bae500-ce61-11e9-8d94-934358c1e4de.png)

I tried to do the transfer like this, didn't work:

![image](https://user-images.githubusercontent.com/19366641/64184007-af057c80-ce62-11e9-888d-cbd05fe78607.png)

I assume I have to be added to the org first?

**Comment by jpmens** [comment]
Can you try again?

**Comment by jpmens** [comment]
Please also send me an email to jp()mens.de and I'll invite you to our MatterMost

**Comment by linusg** [comment]
Still no permission - maybe we can do this the other way around, I sent an invitation for you to join as a collaborator and you transfer?

**Comment by jpmens** [comment]
I got and accepted your invite, thanks, but I don't see how to initiate a transfer ...

**Comment by jpmens** [comment]
what I could do, of course, is fork, but that's not a transfer, i.e. issues/PRs won't come along

**Comment by jpmens** [comment]
Could you try and transfer your repo to `jpmens/frontend` ?

**Comment by jpmens** [comment]
Yay! https://github.com/owntracks/frontend

**Comment by jpmens** [comment]
You should now be maintainer for that repository.

**Comment by linusg** [comment]
I am. Thanks!
