### ISSUE TITLE
GitHub link in OwnTracks booklet site is not actually linked

### ISSUE THREAD

**Issue by unikitty37** [owntracks/talk#74]
The GitHub link at the bottom of the sidebar in the OwnTracks booklet does not have an `href` attribute, and so the link does not actually link anywhere.

```html
<a class="icon icon-github" style="float: left; color: #fcfcfc"> GitHub</a>
```

**Comment by jpmens** [comment]
As far as I can tell from the CSS and the generated HTML, it's supposed to be that way.

**Comment by jpmens** [comment]
I really cannot find where that’s generated from; it’s not in our mkdocs configuration ... If you care to investigate and tell us, I’ll fix it. :-)
