### ISSUE TITLE
Improvement : send reverse geocoding results ?

### ISSUE THREAD

**Issue by ut0py4** [owntracks/talk#77]
Hi,

first of all a big thank you for this wonderful applicaton which works perfectly!

I wanted to submit an improvement proposal: would it be possible to also send the result of the reverse geocoding performed by the Android application (and IOS ...) to the MQTT server?

Since the application does it on the phone, this would avoid doing reverse geocoding on the server for those who use it.

Thanks in advance for the reply.

**Comment by jpmens** [comment]
Thanks for your kind words.

While it would likely be possible to do so, one of the original intentions was to keep the volume of data which is tranferred from smartphone to the backend as low as possible: not everybody has "all-you-can eat" flatrates. :-) 

Our Recorder is capable of doing reverse geo-coding server-side upon receiving payloads, and other possibilities exist, so I don't think we'll make this a feature now.

**Comment by ckrey** [comment]
One more thought on your request:

The iOS (and I guess the Android app does the same thing) only does reverse geo-code when the user requests it (aka looks at the friends screen), not for every location published. 

The reverse geo-coding is rate-limited and must only be used for the UI.

**Comment by ut0py4** [comment]
Thanks for the very quick answers!

I understand for the volume of data. Too bad I didn't necessarily need the recorder and the reverse geocoding solutions are often paid or rate-limited (as @ckrey said).

> The iOS (and I guess the Android app does the same thing) only does reverse geo-code when the user requests it (aka looks at the friends screen), not for every location published.

I asked for this functionality because on my Android phone, adress get from reverse geocoding systematically appears in my notification bar at each change of position (in significant changes mode - the only one I use).

Thanks again.

**Comment by jpmens** [comment]
@jpawlowski I believe we have given sufficient (and in my opinion very valid) reasons why we think this is not a good idea. Telling is that "Geofency would simply do it" is a bit of a slap in the face.

I would like to suggest you then "simply use Geofency" and be done with it.

Of course if you think you prefer to use OwnTracks and want the functionality you are asking for, you might be interested to know OwnTracks is open source; feel free to add whatever feature you desire to your personal copy of it.

**Comment by jpawlowski** [comment]
Well that “slap” was intentionally. Reading a childish response “go and build it yourself from source code, it is open source!” will not make me think I made a mistake here.

Data traffic is not a good reason these days, even in Germany. Other options in the pipeline of this project are supposed to be configurable and so could this.

It is a bit of a slap by its own to refer people installing more and more additional backend components for things that could just be so simple but will then complicate private home infrastructure even more.

Not a good shot in my humble opinion.

**Comment by growse** [comment]
You're very welcome to fork the project.
