### ISSUE TITLE
Remoteconfig

### ISSUE THREAD

**Issue by dmikester1** [owntracks/talk#79]
I found the page titled remoteconfig in your docs hoping it would provide the feature I was looking for.  No dice.  I was hoping there would be an an ability to load a config file from a remote address.  Example: mysite.com/config.otrc. I could see installing this on my parents phones for an idea I had.  But I would want the ability to remotely update their config without having to walk them through downloading it and importing it everytime.  Ideally it would be running in the background on their phones 24/7 with zero interaction or input from them.  It would be sweet to remotely update waypoints and other settings.

**Comment by dmikester1** [comment]
I guess if they never turn off or reboot their phones,  the latest config file would never be imported anyways.  Probably no way to watch for updates and automatically import when change is detected.

**Comment by jpmens** [comment]
As you’ve no doubt read, that’s not what remoteConfig is about. It allows you to push out a configuration to a phone which is connected to an MQTT broker (or HTTP endpoint) you’ve previously configured. So we cannot currently do what you need.

It is a good idea, though.

**Comment by dmikester1** [comment]
Is this something that I can make a feature request for?  Seems like it wouldn't be terribly complicated.  I would even be willing to look into it.  I normally do Javascript development, but I know Java as well.

**Comment by jpmens** [comment]
To be honest I don't see quite why your idea would be more useful than what we have already.

Given, you would simply need to enter a URL for the whole config to be loaded, whereas now we have a bit more configuration to do. However, what is still possible, after an initial configuration is for you to "push" configs out to the remote phones.

An initial configuration can be accomplished by sending your parents a pre-populated `.otrc` file which they just open from, say, an email. I don't see how this is more complicated than entering a URL.

**Comment by dmikester1** [comment]
OK, I didn't know about the ability to "push" configs remotely after initial configuration.  That will work just fine for my purposes, thank you!
