### ISSUE TITLE
Owntracks App for Samsung Smart Watches

### ISSUE THREAD

**Issue by wansti** [owntracks/talk#80]
Hi,
my wife and I have written an Owntracks compatible app based on OpenStreetMap for the Samsung Galaxy series of smartwatches. It can be used as a standalone mapping app, or share the watch's GPS location with an Owntracks server and display other users' locations directly on the watch. I have just submitted it to the Galaxy app store - as soon as the review process is complete I will put the source code on GitHub.

**Comment by jpmens** [comment]
That sounds exciting, thanks for telling us. If you feel like showing us a screenshot here, please go ahead!

**Comment by wansti** [comment]
I'll have to come up with a few more exciting screenshots but here's the main map screen and one that shows a live location from the Android app.

![Screen_20191228_172017](https://user-images.githubusercontent.com/1392063/71542607-9d6d5500-29bc-11ea-9b5b-af81b0d2f4cf.png)

![Screen_20191228_171440](https://user-images.githubusercontent.com/1392063/71542697-87ac5f80-29bd-11ea-85d2-062fb7484f96.png)

Menu items, from left to right:
* Toggle screen always on
* Show debug log
* Place pin (implemented as a location message with "pin" as device ID)
* Remove pin
* Connect to/disconnect from Owntracks server
* Cycle through location markers
* Toggle menu
* Server settings

**Comment by jpmens** [comment]
Very nice.

Don't forget, please, to tell us when you've published the code, and I'll be glad to add your app as a client to our [Booklet](https://owntracks.org/booklet/).

**Comment by wansti** [comment]
Will do, thanks! See previous post for updated screenshots.

**Comment by wansti** [comment]
Hi,
after a lengthy and delayed review process Owntracks OSM is finally available in the Samsung Galaxy App Store! The [source code is available on GitHub](https://github.com/wansti/OwntracksOSM), including a README file with instructions. If you have a compatible watch please give it a try and let me know what you think.

**Comment by jpmens** [comment]
Congratulations. We've added a [mention to our Booklet](https://owntracks.org/booklet/guide/clients/).
