### ISSUE TITLE
Clear iOS notification counter on icon

### ISSUE THREAD

**Issue by thew1se** [owntracks/talk#83]
The notification counter on the OwnTracks icon is always floating around 1000.   Is there a way to turn off the counter or to delete them?  

I still want notifications, just expect the counter to reset to zero when I enter the app or to see a list of what the notifications were within the app with option to mark as “read”.

Thanks!

**Comment by ckrey** [comment]
The "Notification" count on the OwnTracks icon is used to display the number of queued (undelivered) position messages to your backend.

Please check our configuration and backend logs.

Which kind (MQTT/HTTP) backend do you use?

**Comment by thew1se** [comment]
Http.  

I noticed it went down after last night while I was using the app.  About -1 every 2 seconds.   When I closed the app, it continued for about 20-30 seconds then stopped.   When I reopened the app it continued.

**Comment by thew1se** [comment]
I use this app part of a home automation solution so don’t have a need to go into the app regularly.   Is there a way to turn this feature off?

**Comment by ckrey** [comment]
This means your HTTP backend takes about 2 seconds to respond to the iPhone with a positive HTTP response (2xx). 

No, you may delete and re-install, this will reset the queued messages or you may want to clear the backlog by leaving the app on for a little longer.

If 1000 is displayed, this means your backend did not process the latest 1000 position messages.

**Comment by thew1se** [comment]
yup, that's what I did last night...left it on until it cleared on its own.  Thanks.
