### ISSUE TITLE
Owntracks in HTML5 

### ISSUE THREAD

**Issue by roshii** [owntracks/talk#84]
What about porting Owntracks to HTML5?

I run a mosquitto server with a few Android and iOS clients and would love to add a [KaiOS](https://www.kaiostech.com/) based device - running HTML5 applications - to the list. 

I have unfortunately no HTML5 knowledge to help but I'm more than happy to test if it comes to that point.

**Comment by jpmens** [comment]
I’d look, but that web site’s TLS certificate expired 4 days ago. 

Anyway, we’’ll gladly accept your contributions to do so.

**Comment by roshii** [comment]
GerdaOS happens to be a port of KaiOS for the Nokia 8110 4G, I corrected my initial post accordingly. No expired certificate :)

**Comment by sanjeshpathak** [comment]
Thanks for the suggestion. Even I am looking for an Owntracks client app that runs on KaiOS devices and publishes the location data ideally to an MQTT broker.

**Comment by jpmens** [comment]
Closed for inactivity.
