### ISSUE TITLE
Post to owntracks/UserID/DeviceID topic whenever region boundary is passed?

### ISSUE THREAD

**Issue by sheppy99** [owntracks/talk#85]
I've been working at interfacing Owntracks with OpenHAB using MQTT without using the dedicated V1.x Owntracks binding as all V1.x bindings are being retired when the next major version appears. I've noticed that a general update is published to owntracks/UserID/DeviceID around the time a enter or leave message is published to the owntracks/UserID/DeviceID/event topic. Is this expected behaviour? The reason I ask is the general update message contains all the regions the device is currently in and can be used instead of the specific event topic.
I realise there is a HTTP only gpstracker binding but that doesn't work with my scenario.

**Comment by ckrey** [comment]
Yes this is the expected behaviour. 
The `inregions` attribute in the `_location` messages is optional.

**Comment by sheppy99** [comment]
Thanks for the prompt reply
