### ISSUE TITLE
Integrate owntracks in existing app

### ISSUE THREAD

**Issue by ugintl** [owntracks/talk#86]
How to integrate owntracks in existing android and ios apps?

**Comment by jpmens** [comment]
Can you please explain a bit more what you mean exactly?

Our apps already integrate OwnTracks so it’s not clear to me what you are asking.

**Comment by ugintl** [comment]
I mean if someone is developing his own app. Let us say a messenger app and he wants to integrate owntracks in it. Got it?

**Comment by jpmens** [comment]
We have no specific integration into 3rd party apps. As our apps are open source you can, providing you abide by the licenses, use portions of the code. Other than that, our data formats (documented in our Booklet) are used by a few different applications in order to be OwnTracks compatible.
