### ISSUE TITLE
Deployment suggestion: 1-click AWS deployment

### ISSUE THREAD

**Issue by timfernando** [owntracks/talk#89]
After hearing JP's talk on #geomob on the 7th April 2020, it occurred to me that OwnTracks maybe well suited to being one-click deployed to AWS. 

## Why I think this is interesting
* AWS has a free tier which could make it free to run for most users
* AWS Simple Queue Service appears to be MQTT compatible
* A 1-click install could make it take seconds to get new users

**Comment by ckrey** [comment]
One result of the 1-click install should be a configuration file for the smartphone apps (`.otrc`).
(or a set of these for a number of different users sharing the AWS backend)

**Comment by jpmens** [comment]
Closed due to inactivity; feel free to chime in.
