### ISSUE TITLE
Owntracks gets killed by Android

### ISSUE THREAD

**Issue by e7o-de** [owntracks/talk#9]
Hey,

I kept playing a little bit with the app. This is what I observed on a Huawei Mate 9:

04-10 19:11:45.563  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: move high frequent=org.owntracks.android, uid=10170
04-10 19:11:49.515  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: move high frequent=org.owntracks.android, uid=10170
04-10 19:11:53.449  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: not kill critical frequent=org.owntracks.android, uid=10170
04-10 19:11:57.473  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: not kill critical frequent=org.owntracks.android, uid=10170
04-10 19:12:05.495  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: not kill critical frequent=org.owntracks.android, uid=10170
04-10 19:12:21.520  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: not kill critical frequent=org.owntracks.android, uid=10170
04-10 19:12:53.543  1024 15746 W AwareLog: AwareMem_Kill: updateGroupList package: not kill critical frequent=org.owntracks.android, uid=10170
04-10 19:12:59.199  1024  1481 E HwCHRWebMonitor: HwCHRWifiUIDWebSpeed [appName=org.owntracks.android UID=10170  WEBSENDSEGS=1  WEBRESENDSEGS=0  WEBRECVSEGS=2  WEBERRSEGS=0  WEBOUTRSTS=0  WEBESTABLISRST=0  WEBRTTDURATION=0  WEBRTTSEGS=0  WEBSNDDUPACKS=0  suckTimes=0 recovage_times=0]

Happens randomly; memory is still free (~ 50 %); doesn't happen for other phones (like Nexus 5); that magic autocleaner stuff is disabled as far as possible. Also happens to other background tasks, so it's not Owntracks fault :)

Any experiences with that or hints or "workarounds"?

A small issue is that it is triggering a location update even if the phone didn't move (the coords are exactly the same); might make sense to keep the last value persisted.

**Comment by e7o-de** [comment]
Actually, I guess this is interesting as well ;)

04-10 19:11:45.563  1024 15639 W AwareLog: AwareMem_Kill: updateGroupList package: move high frequent=org.owntracks.android, uid=10170
04-10 19:11:45.565  1787  2075 I AppManager: removeProcessDependency pid:15340
04-10 19:11:45.568  1024  1413 E HsmCoreServiceImpl: onTransact in code is: 102
04-10 19:11:45.568  1024  1413 I MediaProcessHandler: processOp opType: 1, uid: 10170, pid: 15340
04-10 19:11:45.568  1024  1413 W MediaProcessHandler: remove target not exist, maybe the UI process: uid: 10170, pid: 15340
04-10 19:11:45.860  1787  9756 I DownloadState: @@@@@@@@@@@@ uid :10184 download :false
04-10 19:11:45.860  1787  9756 I PGServer: report state:5 event type:2 pid:0 uid:10184 pkg:null to pid: 1024
04-10 19:11:45.884  1024  1426 E WifiConfigManager: updateConfiguration freq=2447 <xxxx>
04-10 19:11:46.172  2550  8520 W ctxmgr  : [AclManager]No 2 for (accnt=account#-1046213244#, com.google.android.gms(10015):UserLocationProducer, vrsn=10298000, 0, 3pPkg = null ,  3pMdlId = null). Was: 2 for 1, account#-1046213244#
04-10 19:11:46.588 15641 15641 I         : power log dlsym ok
04-10 19:11:46.591 15641 15641 I art     : Reinit property: dalvik.vm.checkjni= false
04-10 19:11:46.634   486  2938 I gralloc : alloc_device_alloc:564: Alloc handle(0x77629fe200): interfmt=1, stride=64, size=4096, usage=0x100
04-10 19:11:46.649   486  2938 I gralloc : alloc_device_free:586: Free handle(0x77629fe200)
04-10 19:11:46.667 15641 15641 I art     : Starting a blocking GC AddRemoveAppImageSpace
04-10 19:11:46.675 15641 15641 W art     : JIT profile information will not be recorded: profile file does not exits.

**Comment by binarybucks** [comment]
What is interesting about that last part? 

Android may kill apps as it likes. Do you have the ongoing notification enabled? It greatly reduces the likelihood that the app is killed in the background. 

If some crappy OS component ia wreaking havoc, there's not much that we can do. I'm not familiar with Huawai phones but maybe there is a whitelist for that behavior.

**Comment by e7o-de** [comment]
Not sure if it's interesting, just wanted to talk about that :) I mean, I can life with duplicated events, that's ok. Notification is enabled, yes, it still happens on that phone. Other phones seems to be not affected ... Interesting part is that there's no Google result for "AwareMem_Kill", maybe somebody will find his way to this thread?

**Comment by e7o-de** [comment]
Actually, I noticed an issue with this behaviour: The queue gets emptied, as you're storing the data only in memory and not persisting it. That's not an optimal behaviour then ...
