### ISSUE TITLE
OwnTracks Recorder & Frontend Combo Docker-Compose

### ISSUE THREAD

**Issue by Unkn0wnCat** [owntracks/talk#90]
Hi OwnTracks-Contributers,

I've used a custom docker-compose config and a matching NGINX config for mine and a friends deployment of Recorder and Frontend and I thought this might help others in search of a easy, one-stop installation for both. I've not found an official repo on the OwnTracks account this would be a fit for, so I decided to host it in a [new repo on my account (Unkn0wnCat/OwnTracksDockerCombo)](https://github.com/Unkn0wnCat/OwnTracksDockerCombo) for now. I just wanted to share this back to you all, so it may be merged into the official OwnTracks account or the docs if it is deemed useful.

Let me know what you think or if you have an idea where I can merge this into the official repos!

Have a nice day and stay safe,
Kevin Kandlbinder

**Comment by jpmens** [comment]
Repository is now 404 apparently.

**Comment by jonniepanda** [comment]
Did this ever get posted somewhere else? I'd be interested in taking a look. Struggling to get these playing nicely.

Thanks in advance.

**Comment by jpmens** [comment]
You might have a bit of luck at [owntracks/docker-recorder](https://github.com/owntracks/docker-recorder).

**Comment by Unkn0wnCat** [comment]
Hey @jonniepanda,

I've private-archived the [repo](https://github.com/Unkn0wnCat/OwnTracksDockerCombo) a while back because it didn't seem that useful, so I abandoned it. But I've just changed back the visibility to public archive, so you can use it as a reference! You will need to update the version tags, but otherwise this should still be functioning out of the box (it's the setup I still use to this day)

Hope this helps!

**Comment by jonniepanda** [comment]
that's great, I'll take a look - cheers 👍
