### ISSUE TITLE
From Owntrack to QGIS

### ISSUE THREAD

**Issue by x821938** [owntracks/talk#91]
If anyone is interested, I made a couple of blog postings about how to collect Owntrack data in a MySQL database, and then import it directly into [QGIS](https://www.qgis.org).

[https://www.cron.dk/from-owntrack-to-qgis-part-1/](https://www.cron.dk/from-owntrack-to-qgis-part-1/)
[https://www.cron.dk/from-owntrack-to-qgis-part-2/](https://www.cron.dk/from-owntrack-to-qgis-part-2/)

The links could be added to your booklet under section clients->related?
[https://owntracks.org/booklet/guide/clients/#related](https://owntracks.org/booklet/guide/clients/#related)

Best regards,
    Alex

**Comment by jpmens** [comment]
Thank you for the heads up; I've added a link [to our Booklet](https://owntracks.org/booklet/guide/clients/) as you suggested.
