### ISSUE TITLE
Another use for owntracks data

### ISSUE THREAD

**Issue by BrianHepler** [owntracks/talk#97]
First, thank you to the team for helping me out with my application. It's a bit of a specialty application, but I created a module for the MagicMirror2 framework. I created a virtual Weasley Clock which you can display on your magic mirror.

You can find the module at [MMM-WeasleyClock](https://github.com/BrianHepler/MMM-WeasleyClock).

**Comment by jpmens** [comment]
Thank you, @BrianHepler; we've added a link to your project from our Clients page in the Booklet.
